SUMMARY = "WiseKiosk frontend: the static bundle the kiosk displays"
DESCRIPTION = "A Svelte single-page bundle, generated by vite from the app's own source. Before vite \
runs, orval and json2ts regenerate the API client and the config types from the app's own OpenAPI \
and JSON schema, so nothing generated reaches git. There is no runtime here -- the output is HTML, \
JS, CSS and a font, served by wisekiosk-backend out of /srv/kiosk. Built from source rather than \
consumed as an artifact from the app's CI because it is a static-site generator: the inputs are \
pinned and the output is a directory of files."

require wisekiosk-src.inc

LIC_FILES_CHKSUM = "file://LICENSE;md5=4af5bdd6287d36bddd2161cdad4e1eb5"

# `;dev=1`: every package in the shrinkwrap is a devDependency, vite included,
# and the closure resolves empty without it. The npmsw path is literal, not
# searched through FILESPATH. destsuffix puts node_modules beside the app's
# package.json at git/frontend, where node resolves imports by walking up.
SRC_URI += "npmsw://${THISDIR}/${BPN}/npm-shrinkwrap.json;dev=1;destsuffix=git/frontend"

# The shrinkwrap above is gitignored and written by tools/app-lockfile.py at
# build entry (owner, 2026-09-27: nothing autogenerable is committed), so a
# tree that never ran it, or one still holding a previous pin's shrinkwrap,
# parses here with no warning otherwise -- same shape as
# meta-wisekiosk/classes/kiosk-buildinfo-cachesafe.bbclass's check on
# KIOSK_BUILDINFO_REV. The shrinkwrap is a plain JSON file, not `require`d, so
# its <shrinkwrap>.srcrev stamp is read directly rather than as a bitbake var.
python () {
    import os
    stamp = os.path.join(d.getVar('THISDIR'), d.getVar('BPN'),
                          'npm-shrinkwrap.json.srcrev')
    recorded = open(stamp).read().strip() if os.path.exists(stamp) else None
    if recorded != d.getVar('SRCREV'):
        bb.fatal("npm-shrinkwrap.json is missing or stale for this SRCREV: "
                 "run `just build`, or any other entry point that runs "
                 "tools/app-lockfile.py, before bitbake.")
}

# Build-host only, and no `inherit npm`: npmsw places the closure and the
# deliverable is the emitted bundle, not a target module.
DEPENDS = "nodejs-binary-native"

S = "${WORKDIR}/git"

do_compile() {
    cd ${S}/frontend
    # orval emits through prettier; an unformatted-but-valid pass would hide
    # that prettier silently stopped resolving.
    node --input-type=module -e "await import('prettier')" || bbfatal "prettier not importable; orval would emit unformatted code"
    node node_modules/orval/dist/bin/orval.mjs
    node node_modules/json-schema-to-typescript/dist/src/cli.js --input src/config/schema.json --output src/config/types.ts --additionalProperties false
    node node_modules/vite/bin/vite.js build
}

do_install() {
    install -d ${D}/srv/kiosk
    cp -R --no-dereference --preserve=mode,timestamps ${S}/frontend/dist/. ${D}/srv/kiosk/

    # Site configuration lives in /data, not baked into the image. The backend
    # serves this tree per request through http.Dir, which follows the link, so
    # a file written to /data later needs no restart; kiosk-seed-config seeds
    # config.json from the example installed below when /data holds none yet.
    ln -s /data/config/config.json ${D}/srv/kiosk/config.json

    install -D -m 0644 ${S}/deploy/config.example.json ${D}${datadir}/wisekiosk/config.example.json
}

FILES:${PN} = "/srv/kiosk"
FILES:${PN} += "${datadir}/wisekiosk"
