HTTP/1.1 200 OK
Date: Fri, 09 Oct 2026 13:03:34 GMT
Content-Type: application/json; charset=utf-8
access-control-allow-origin: *
access-control-expose-headers: RateLimit-Limit,RateLimit-Policy,RateLimit-Remaining,RateLimit-Reset,RateLimit-History-Limit,RateLimit-History-Policy,RateLimit-History-Remaining,RateLimit-History-Reset,Retry-After
cache-control: public, max-age=300, s-maxage=3600
content-security-policy: default-src 'self';style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://unpkg.com;script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://unpkg.com;font-src 'self' https://cdn.jsdelivr.net;connect-src 'self' https://unpkg.com https://cdn.jsdelivr.net;img-src 'self' data: https:;base-uri 'self';form-action 'self';frame-ancestors 'self';object-src 'none';script-src-attr 'none';upgrade-insecure-requests
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-origin
etag: W/"14e9-Rt/VjvYoRYXNOjZ/JVdq+MZuMXQ"
nel: {"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}
origin-agent-cluster: ?1
ratelimit-limit: 300
ratelimit-policy: 300;w=60
ratelimit-remaining: 299
ratelimit-reset: 60
referrer-policy: no-referrer
report-to: {"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=LNyybDtkSIAQm45RhUqSNxyES9f0T1U3k9K%2FNWv6b%2Fg%3D\u0026sid=c4c9725f-1ab0-44d8-820f-430df2718e11\u0026ts=1791520545"}],"max_age":3600}
reporting-endpoints: heroku-nel="https://nel.heroku.com/reports?s=LNyybDtkSIAQm45RhUqSNxyES9f0T1U3k9K%2FNWv6b%2Fg%3D&sid=c4c9725f-1ab0-44d8-820f-430df2718e11&ts=1791520545"
Server: cloudflare
strict-transport-security: max-age=2592000
vary: Accept-Encoding
via: 2.0 heroku-router
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-request-id: 54911d4c-dbfa-de7d-3df4-8b54728f2dea
x-xss-protection: 0
cf-cache-status: HIT
Age: 1620
CF-RAY: a47d9612fdcfac95-MIA
alt-svc: h3=":443"; ma=86400
Content-Length: 5353

{
  "id": "ead53ea5-22e5-4095-9a83-8c29300d7c63",
  "name": "Disney's Blizzard Beach Water Park",
  "entityType": "PARK",
  "timezone": "America/New_York",
  "schedule": [
    {
      "date": "2026-10-09",
      "type": "OPERATING",
      "closingTime": "2026-10-09T17:00:00-04:00",
      "openingTime": "2026-10-09T10:00:00-04:00"
    },
    {
      "date": "2026-10-10",
      "type": "OPERATING",
      "closingTime": "2026-10-10T17:00:00-04:00",
      "openingTime": "2026-10-10T10:00:00-04:00"
    },
    {
      "date": "2026-10-11",
      "type": "OPERATING",
      "closingTime": "2026-10-11T17:00:00-04:00",
      "openingTime": "2026-10-11T10:00:00-04:00"
    },
    {
      "date": "2026-10-12",
      "type": "OPERATING",
      "closingTime": "2026-10-12T17:00:00-04:00",
      "openingTime": "2026-10-12T10:00:00-04:00"
    },
    {
      "date": "2026-10-13",
      "type": "OPERATING",
      "closingTime": "2026-10-13T17:00:00-04:00",
      "openingTime": "2026-10-13T10:00:00-04:00"
    },
    {
      "date": "2026-10-14",
      "type": "OPERATING",
      "closingTime": "2026-10-14T17:00:00-04:00",
      "openingTime": "2026-10-14T10:00:00-04:00"
    },
    {
      "date": "2026-10-15",
      "type": "OPERATING",
      "closingTime": "2026-10-15T17:00:00-04:00",
      "openingTime": "2026-10-15T10:00:00-04:00"
    },
    {
      "date": "2026-10-16",
      "type": "OPERATING",
      "closingTime": "2026-10-16T17:00:00-04:00",
      "openingTime": "2026-10-16T10:00:00-04:00"
    },
    {
      "date": "2026-10-17",
      "type": "OPERATING",
      "closingTime": "2026-10-17T17:00:00-04:00",
      "openingTime": "2026-10-17T10:00:00-04:00"
    },
    {
      "date": "2026-10-18",
      "type": "OPERATING",
      "closingTime": "2026-10-18T17:00:00-04:00",
      "openingTime": "2026-10-18T10:00:00-04:00"
    },
    {
      "date": "2026-10-19",
      "type": "OPERATING",
      "closingTime": "2026-10-19T17:00:00-04:00",
      "openingTime": "2026-10-19T10:00:00-04:00"
    },
    {
      "date": "2026-10-20",
      "type": "OPERATING",
      "closingTime": "2026-10-20T17:00:00-04:00",
      "openingTime": "2026-10-20T10:00:00-04:00"
    },
    {
      "date": "2026-10-21",
      "type": "OPERATING",
      "closingTime": "2026-10-21T17:00:00-04:00",
      "openingTime": "2026-10-21T10:00:00-04:00"
    },
    {
      "date": "2026-10-22",
      "type": "OPERATING",
      "closingTime": "2026-10-22T17:00:00-04:00",
      "openingTime": "2026-10-22T10:00:00-04:00"
    },
    {
      "date": "2026-10-23",
      "type": "OPERATING",
      "closingTime": "2026-10-23T17:00:00-04:00",
      "openingTime": "2026-10-23T10:00:00-04:00"
    },
    {
      "date": "2026-10-24",
      "type": "OPERATING",
      "closingTime": "2026-10-24T17:00:00-04:00",
      "openingTime": "2026-10-24T10:00:00-04:00"
    },
    {
      "date": "2026-10-25",
      "type": "OPERATING",
      "closingTime": "2026-10-25T17:00:00-04:00",
      "openingTime": "2026-10-25T10:00:00-04:00"
    },
    {
      "date": "2026-10-26",
      "type": "OPERATING",
      "closingTime": "2026-10-26T17:00:00-04:00",
      "openingTime": "2026-10-26T10:00:00-04:00"
    },
    {
      "date": "2026-10-27",
      "type": "OPERATING",
      "closingTime": "2026-10-27T17:00:00-04:00",
      "openingTime": "2026-10-27T10:00:00-04:00"
    },
    {
      "date": "2026-10-28",
      "type": "OPERATING",
      "closingTime": "2026-10-28T17:00:00-04:00",
      "openingTime": "2026-10-28T10:00:00-04:00"
    },
    {
      "date": "2026-10-29",
      "type": "OPERATING",
      "closingTime": "2026-10-29T17:00:00-04:00",
      "openingTime": "2026-10-29T10:00:00-04:00"
    },
    {
      "date": "2026-10-30",
      "type": "OPERATING",
      "closingTime": "2026-10-30T17:00:00-04:00",
      "openingTime": "2026-10-30T10:00:00-04:00"
    },
    {
      "date": "2026-10-31",
      "type": "OPERATING",
      "closingTime": "2026-10-31T17:00:00-04:00",
      "openingTime": "2026-10-31T10:00:00-04:00"
    },
    {
      "date": "2026-11-01",
      "type": "OPERATING",
      "closingTime": "2026-11-01T17:00:00-05:00",
      "openingTime": "2026-11-01T10:00:00-05:00"
    },
    {
      "date": "2026-11-02",
      "type": "OPERATING",
      "closingTime": "2026-11-02T17:00:00-05:00",
      "openingTime": "2026-11-02T10:00:00-05:00"
    },
    {
      "date": "2026-11-03",
      "type": "OPERATING",
      "closingTime": "2026-11-03T17:00:00-05:00",
      "openingTime": "2026-11-03T10:00:00-05:00"
    },
    {
      "date": "2026-11-04",
      "type": "OPERATING",
      "closingTime": "2026-11-04T17:00:00-05:00",
      "openingTime": "2026-11-04T10:00:00-05:00"
    },
    {
      "date": "2026-11-05",
      "type": "OPERATING",
      "closingTime": "2026-11-05T17:00:00-05:00",
      "openingTime": "2026-11-05T10:00:00-05:00"
    },
    {
      "date": "2026-11-06",
      "type": "OPERATING",
      "closingTime": "2026-11-06T17:00:00-05:00",
      "openingTime": "2026-11-06T10:00:00-05:00"
    },
    {
      "date": "2026-11-07",
      "type": "OPERATING",
      "closingTime": "2026-11-07T17:00:00-05:00",
      "openingTime": "2026-11-07T10:00:00-05:00"
    },
    {
      "date": "2026-11-08",
      "type": "OPERATING",
      "closingTime": "2026-11-08T17:00:00-05:00",
      "openingTime": "2026-11-08T10:00:00-05:00"
    }
  ]
}