HTTP/1.1 200 OK
Date: Fri, 09 Oct 2026 13:03:35 GMT
Content-Type: application/json; charset=utf-8
access-control-allow-origin: *
access-control-expose-headers: RateLimit-Limit,RateLimit-Policy,RateLimit-Remaining,RateLimit-Reset,RateLimit-History-Limit,RateLimit-History-Policy,RateLimit-History-Remaining,RateLimit-History-Reset,Retry-After
Cache-Control: public, max-age=300, s-maxage=3600
content-security-policy: default-src 'self';style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://unpkg.com;script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://unpkg.com;font-src 'self' https://cdn.jsdelivr.net;connect-src 'self' https://unpkg.com https://cdn.jsdelivr.net;img-src 'self' data: https:;base-uri 'self';form-action 'self';frame-ancestors 'self';object-src 'none';script-src-attr 'none';upgrade-insecure-requests
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-origin
etag: W/"9fd9-rYI8JeqeR3JpKs1ACZJ1y9ZC9+Q"
nel: {"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}
origin-agent-cluster: ?1
ratelimit-limit: 300
ratelimit-policy: 300;w=60
ratelimit-remaining: 298
ratelimit-reset: 1
referrer-policy: no-referrer
report-to: {"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=ZKaXXEtbsY%2Bc8MrLj9FxCsdBH5q%2FBQU5qHm7g4ECsqU%3D\u0026sid=c4c9725f-1ab0-44d8-820f-430df2718e11\u0026ts=1791550091"}],"max_age":3600}
reporting-endpoints: heroku-nel="https://nel.heroku.com/reports?s=ZKaXXEtbsY%2Bc8MrLj9FxCsdBH5q%2FBQU5qHm7g4ECsqU%3D&sid=c4c9725f-1ab0-44d8-820f-430df2718e11&ts=1791550091"
Server: cloudflare
strict-transport-security: max-age=2592000
vary: Accept-Encoding
via: 2.0 heroku-router
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-request-id: 1836b9a5-ada5-090b-9a50-2ff4c6ef3485
x-xss-protection: 0
cf-cache-status: HIT
Age: 924
CF-RAY: a47d9615e8961f66-MIA
alt-svc: h3=":443"; ma=86400
Content-Length: 40921

{
  "id": "75ea578a-adc8-4116-a54d-dccb60765ef9",
  "name": "Magic Kingdom Park",
  "entityType": "PARK",
  "timezone": "America/New_York",
  "schedule": [
    {
      "date": "2026-10-09",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-09T08:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-09T07:30:00-04:00"
    },
    {
      "date": "2026-10-09",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1400,
            "currency": "USD",
            "formatted": "$14.00"
          },
          "available": false
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2300,
            "currency": "USD",
            "formatted": "$23.00"
          },
          "available": false
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3700,
            "currency": "USD",
            "formatted": "$37.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-09T18:00:00-04:00",
      "openingTime": "2026-10-09T08:00:00-04:00"
    },
    {
      "date": "2026-10-09",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-10T00:00:00-04:00",
      "description": "Special Ticketed Event",
      "openingTime": "2026-10-09T19:00:00-04:00"
    },
    {
      "date": "2026-10-10",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-10T08:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-10T07:30:00-04:00"
    },
    {
      "date": "2026-10-10",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1500,
            "currency": "USD",
            "formatted": "$15.00"
          },
          "available": false
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2300,
            "currency": "USD",
            "formatted": "$23.00"
          },
          "available": false
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3900,
            "currency": "USD",
            "formatted": "$39.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-10T23:00:00-04:00",
      "openingTime": "2026-10-10T08:00:00-04:00"
    },
    {
      "date": "2026-10-11",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-11T08:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-11T07:30:00-04:00"
    },
    {
      "date": "2026-10-11",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1500,
            "currency": "USD",
            "formatted": "$15.00"
          },
          "available": false
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2300,
            "currency": "USD",
            "formatted": "$23.00"
          },
          "available": false
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3900,
            "currency": "USD",
            "formatted": "$39.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-11T23:00:00-04:00",
      "openingTime": "2026-10-11T08:00:00-04:00"
    },
    {
      "date": "2026-10-12",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-12T09:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-12T08:30:00-04:00"
    },
    {
      "date": "2026-10-12",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1500,
            "currency": "USD",
            "formatted": "$15.00"
          },
          "available": false
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2300,
            "currency": "USD",
            "formatted": "$23.00"
          },
          "available": false
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3700,
            "currency": "USD",
            "formatted": "$37.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-12T22:00:00-04:00",
      "openingTime": "2026-10-12T09:00:00-04:00"
    },
    {
      "date": "2026-10-13",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-13T08:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-13T07:30:00-04:00"
    },
    {
      "date": "2026-10-13",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1400,
            "currency": "USD",
            "formatted": "$14.00"
          },
          "available": false
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2200,
            "currency": "USD",
            "formatted": "$22.00"
          },
          "available": false
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3500,
            "currency": "USD",
            "formatted": "$35.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-13T18:00:00-04:00",
      "openingTime": "2026-10-13T08:00:00-04:00"
    },
    {
      "date": "2026-10-13",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-14T00:00:00-04:00",
      "description": "Special Ticketed Event",
      "openingTime": "2026-10-13T19:00:00-04:00"
    },
    {
      "date": "2026-10-14",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-14T08:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-14T07:30:00-04:00"
    },
    {
      "date": "2026-10-14",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1500,
            "currency": "USD",
            "formatted": "$15.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2300,
            "currency": "USD",
            "formatted": "$23.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3700,
            "currency": "USD",
            "formatted": "$37.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-14T23:00:00-04:00",
      "openingTime": "2026-10-14T08:00:00-04:00"
    },
    {
      "date": "2026-10-15",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-15T08:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-15T07:30:00-04:00"
    },
    {
      "date": "2026-10-15",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1400,
            "currency": "USD",
            "formatted": "$14.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2200,
            "currency": "USD",
            "formatted": "$22.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3200,
            "currency": "USD",
            "formatted": "$32.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-15T18:00:00-04:00",
      "openingTime": "2026-10-15T08:00:00-04:00"
    },
    {
      "date": "2026-10-15",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-16T00:00:00-04:00",
      "description": "Special Ticketed Event",
      "openingTime": "2026-10-15T19:00:00-04:00"
    },
    {
      "date": "2026-10-16",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-16T08:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-16T07:30:00-04:00"
    },
    {
      "date": "2026-10-16",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1400,
            "currency": "USD",
            "formatted": "$14.00"
          },
          "available": false
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2300,
            "currency": "USD",
            "formatted": "$23.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3900,
            "currency": "USD",
            "formatted": "$39.00"
          },
          "available": true
        },
        {
          "id": "premierpass_80007944",
          "name": "Lightning Lane Premier Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 41900,
            "currency": "USD",
            "formatted": "$419.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-16T18:00:00-04:00",
      "openingTime": "2026-10-16T08:00:00-04:00"
    },
    {
      "date": "2026-10-16",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-17T00:00:00-04:00",
      "description": "Special Ticketed Event",
      "openingTime": "2026-10-16T19:00:00-04:00"
    },
    {
      "date": "2026-10-17",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-17T08:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-17T07:30:00-04:00"
    },
    {
      "date": "2026-10-17",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1500,
            "currency": "USD",
            "formatted": "$15.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2300,
            "currency": "USD",
            "formatted": "$23.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3900,
            "currency": "USD",
            "formatted": "$39.00"
          },
          "available": true
        },
        {
          "id": "premierpass_80007944",
          "name": "Lightning Lane Premier Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 42900,
            "currency": "USD",
            "formatted": "$429.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-17T23:00:00-04:00",
      "openingTime": "2026-10-17T08:00:00-04:00"
    },
    {
      "date": "2026-10-18",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-18T08:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-18T07:30:00-04:00"
    },
    {
      "date": "2026-10-18",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1400,
            "currency": "USD",
            "formatted": "$14.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2200,
            "currency": "USD",
            "formatted": "$22.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3500,
            "currency": "USD",
            "formatted": "$35.00"
          },
          "available": true
        },
        {
          "id": "premierpass_80007944",
          "name": "Lightning Lane Premier Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 41900,
            "currency": "USD",
            "formatted": "$419.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-18T18:00:00-04:00",
      "openingTime": "2026-10-18T08:00:00-04:00"
    },
    {
      "date": "2026-10-18",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-19T00:00:00-04:00",
      "description": "Special Ticketed Event",
      "openingTime": "2026-10-18T19:00:00-04:00"
    },
    {
      "date": "2026-10-19",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-19T09:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-19T08:30:00-04:00"
    },
    {
      "date": "2026-10-19",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1500,
            "currency": "USD",
            "formatted": "$15.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2300,
            "currency": "USD",
            "formatted": "$23.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3500,
            "currency": "USD",
            "formatted": "$35.00"
          },
          "available": true
        },
        {
          "id": "premierpass_80007944",
          "name": "Lightning Lane Premier Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 42900,
            "currency": "USD",
            "formatted": "$429.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-19T22:00:00-04:00",
      "openingTime": "2026-10-19T09:00:00-04:00"
    },
    {
      "date": "2026-10-20",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-20T09:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-20T08:30:00-04:00"
    },
    {
      "date": "2026-10-20",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1500,
            "currency": "USD",
            "formatted": "$15.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2300,
            "currency": "USD",
            "formatted": "$23.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3500,
            "currency": "USD",
            "formatted": "$35.00"
          },
          "available": true
        },
        {
          "id": "premierpass_80007944",
          "name": "Lightning Lane Premier Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 41900,
            "currency": "USD",
            "formatted": "$419.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-20T22:00:00-04:00",
      "openingTime": "2026-10-20T09:00:00-04:00"
    },
    {
      "date": "2026-10-21",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-21T09:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-21T08:30:00-04:00"
    },
    {
      "date": "2026-10-21",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1500,
            "currency": "USD",
            "formatted": "$15.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2300,
            "currency": "USD",
            "formatted": "$23.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3500,
            "currency": "USD",
            "formatted": "$35.00"
          },
          "available": true
        },
        {
          "id": "premierpass_80007944",
          "name": "Lightning Lane Premier Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 41900,
            "currency": "USD",
            "formatted": "$419.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-21T22:00:00-04:00",
      "openingTime": "2026-10-21T09:00:00-04:00"
    },
    {
      "date": "2026-10-22",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-22T09:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-22T08:30:00-04:00"
    },
    {
      "date": "2026-10-22",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1400,
            "currency": "USD",
            "formatted": "$14.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2200,
            "currency": "USD",
            "formatted": "$22.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 2900,
            "currency": "USD",
            "formatted": "$29.00"
          },
          "available": true
        },
        {
          "id": "premierpass_80007944",
          "name": "Lightning Lane Premier Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 37900,
            "currency": "USD",
            "formatted": "$379.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-22T18:00:00-04:00",
      "openingTime": "2026-10-22T09:00:00-04:00"
    },
    {
      "date": "2026-10-22",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-23T00:00:00-04:00",
      "description": "Special Ticketed Event",
      "openingTime": "2026-10-22T19:00:00-04:00"
    },
    {
      "date": "2026-10-23",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-23T08:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-23T07:30:00-04:00"
    },
    {
      "date": "2026-10-23",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1400,
            "currency": "USD",
            "formatted": "$14.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2200,
            "currency": "USD",
            "formatted": "$22.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3500,
            "currency": "USD",
            "formatted": "$35.00"
          },
          "available": true
        },
        {
          "id": "premierpass_80007944",
          "name": "Lightning Lane Premier Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 39900,
            "currency": "USD",
            "formatted": "$399.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-23T18:00:00-04:00",
      "openingTime": "2026-10-23T08:00:00-04:00"
    },
    {
      "date": "2026-10-23",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-24T00:00:00-04:00",
      "description": "Special Ticketed Event",
      "openingTime": "2026-10-23T19:00:00-04:00"
    },
    {
      "date": "2026-10-24",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-24T08:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-24T07:30:00-04:00"
    },
    {
      "date": "2026-10-24",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1500,
            "currency": "USD",
            "formatted": "$15.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2300,
            "currency": "USD",
            "formatted": "$23.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3900,
            "currency": "USD",
            "formatted": "$39.00"
          },
          "available": true
        },
        {
          "id": "premierpass_80007944",
          "name": "Lightning Lane Premier Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 42900,
            "currency": "USD",
            "formatted": "$429.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-24T23:00:00-04:00",
      "openingTime": "2026-10-24T08:00:00-04:00"
    },
    {
      "date": "2026-10-25",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-25T09:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-25T08:30:00-04:00"
    },
    {
      "date": "2026-10-25",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1400,
            "currency": "USD",
            "formatted": "$14.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2300,
            "currency": "USD",
            "formatted": "$23.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3200,
            "currency": "USD",
            "formatted": "$32.00"
          },
          "available": true
        },
        {
          "id": "premierpass_80007944",
          "name": "Lightning Lane Premier Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 39900,
            "currency": "USD",
            "formatted": "$399.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-25T18:00:00-04:00",
      "openingTime": "2026-10-25T09:00:00-04:00"
    },
    {
      "date": "2026-10-25",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-26T00:00:00-04:00",
      "description": "Special Ticketed Event",
      "openingTime": "2026-10-25T19:00:00-04:00"
    },
    {
      "date": "2026-10-26",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-26T09:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-26T08:30:00-04:00"
    },
    {
      "date": "2026-10-26",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1400,
            "currency": "USD",
            "formatted": "$14.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2300,
            "currency": "USD",
            "formatted": "$23.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3500,
            "currency": "USD",
            "formatted": "$35.00"
          },
          "available": true
        },
        {
          "id": "premierpass_80007944",
          "name": "Lightning Lane Premier Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 41900,
            "currency": "USD",
            "formatted": "$419.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-26T22:00:00-04:00",
      "openingTime": "2026-10-26T09:00:00-04:00"
    },
    {
      "date": "2026-10-27",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-27T09:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-27T08:30:00-04:00"
    },
    {
      "date": "2026-10-27",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1300,
            "currency": "USD",
            "formatted": "$13.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2100,
            "currency": "USD",
            "formatted": "$21.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 2900,
            "currency": "USD",
            "formatted": "$29.00"
          },
          "available": true
        },
        {
          "id": "premierpass_80007944",
          "name": "Lightning Lane Premier Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 37900,
            "currency": "USD",
            "formatted": "$379.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-27T18:00:00-04:00",
      "openingTime": "2026-10-27T09:00:00-04:00"
    },
    {
      "date": "2026-10-27",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-28T00:00:00-04:00",
      "description": "Special Ticketed Event",
      "openingTime": "2026-10-27T19:00:00-04:00"
    },
    {
      "date": "2026-10-28",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-28T09:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-28T08:30:00-04:00"
    },
    {
      "date": "2026-10-28",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1400,
            "currency": "USD",
            "formatted": "$14.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2100,
            "currency": "USD",
            "formatted": "$21.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3500,
            "currency": "USD",
            "formatted": "$35.00"
          },
          "available": true
        },
        {
          "id": "premierpass_80007944",
          "name": "Lightning Lane Premier Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 39900,
            "currency": "USD",
            "formatted": "$399.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-28T22:00:00-04:00",
      "openingTime": "2026-10-28T09:00:00-04:00"
    },
    {
      "date": "2026-10-29",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-29T09:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-29T08:30:00-04:00"
    },
    {
      "date": "2026-10-29",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1300,
            "currency": "USD",
            "formatted": "$13.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2200,
            "currency": "USD",
            "formatted": "$22.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3200,
            "currency": "USD",
            "formatted": "$32.00"
          },
          "available": true
        },
        {
          "id": "premierpass_80007944",
          "name": "Lightning Lane Premier Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 37900,
            "currency": "USD",
            "formatted": "$379.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-29T18:00:00-04:00",
      "openingTime": "2026-10-29T09:00:00-04:00"
    },
    {
      "date": "2026-10-29",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-30T00:00:00-04:00",
      "description": "Special Ticketed Event",
      "openingTime": "2026-10-29T19:00:00-04:00"
    },
    {
      "date": "2026-10-30",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-30T09:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-30T08:30:00-04:00"
    },
    {
      "date": "2026-10-30",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1500,
            "currency": "USD",
            "formatted": "$15.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2300,
            "currency": "USD",
            "formatted": "$23.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3500,
            "currency": "USD",
            "formatted": "$35.00"
          },
          "available": true
        },
        {
          "id": "premierpass_80007944",
          "name": "Lightning Lane Premier Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 42900,
            "currency": "USD",
            "formatted": "$429.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-30T22:00:00-04:00",
      "openingTime": "2026-10-30T09:00:00-04:00"
    },
    {
      "date": "2026-10-31",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-10-31T09:00:00-04:00",
      "description": "Early Entry",
      "openingTime": "2026-10-31T08:30:00-04:00"
    },
    {
      "date": "2026-10-31",
      "type": "OPERATING",
      "purchases": [
        {
          "id": "lightninglane_16767284",
          "name": "Lightning Lane for Seven Dwarfs Mine Train",
          "type": "ATTRACTION",
          "price": {
            "amount": 1500,
            "currency": "USD",
            "formatted": "$15.00"
          },
          "available": true
        },
        {
          "id": "lightninglane_411504498",
          "name": "Lightning Lane for TRON Lightcycle / Run",
          "type": "ATTRACTION",
          "price": {
            "amount": 2300,
            "currency": "USD",
            "formatted": "$23.00"
          },
          "available": true
        },
        {
          "id": "lightninglanemultipass_80007944",
          "name": "Lightning Lane Multi Pass",
          "type": "PACKAGE",
          "price": {
            "amount": 3500,
            "currency": "USD",
            "formatted": "$35.00"
          },
          "available": true
        }
      ],
      "closingTime": "2026-10-31T18:00:00-04:00",
      "openingTime": "2026-10-31T09:00:00-04:00"
    },
    {
      "date": "2026-10-31",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-11-01T00:00:00-04:00",
      "description": "Special Ticketed Event",
      "openingTime": "2026-10-31T19:00:00-04:00"
    },
    {
      "date": "2026-11-01",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-11-01T09:00:00-05:00",
      "description": "Early Entry",
      "openingTime": "2026-11-01T08:30:00-05:00"
    },
    {
      "date": "2026-11-01",
      "type": "OPERATING",
      "closingTime": "2026-11-01T22:00:00-05:00",
      "openingTime": "2026-11-01T09:00:00-05:00"
    },
    {
      "date": "2026-11-02",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-11-02T09:00:00-05:00",
      "description": "Early Entry",
      "openingTime": "2026-11-02T08:30:00-05:00"
    },
    {
      "date": "2026-11-02",
      "type": "OPERATING",
      "closingTime": "2026-11-02T22:00:00-05:00",
      "openingTime": "2026-11-02T09:00:00-05:00"
    },
    {
      "date": "2026-11-03",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-11-03T09:00:00-05:00",
      "description": "Early Entry",
      "openingTime": "2026-11-03T08:30:00-05:00"
    },
    {
      "date": "2026-11-03",
      "type": "OPERATING",
      "closingTime": "2026-11-03T22:00:00-05:00",
      "openingTime": "2026-11-03T09:00:00-05:00"
    },
    {
      "date": "2026-11-04",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-11-04T09:00:00-05:00",
      "description": "Early Entry",
      "openingTime": "2026-11-04T08:30:00-05:00"
    },
    {
      "date": "2026-11-04",
      "type": "OPERATING",
      "closingTime": "2026-11-04T22:00:00-05:00",
      "openingTime": "2026-11-04T09:00:00-05:00"
    },
    {
      "date": "2026-11-05",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-11-05T09:00:00-05:00",
      "description": "Early Entry",
      "openingTime": "2026-11-05T08:30:00-05:00"
    },
    {
      "date": "2026-11-05",
      "type": "OPERATING",
      "closingTime": "2026-11-05T22:00:00-05:00",
      "openingTime": "2026-11-05T09:00:00-05:00"
    },
    {
      "date": "2026-11-06",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-11-06T09:00:00-05:00",
      "description": "Early Entry",
      "openingTime": "2026-11-06T08:30:00-05:00"
    },
    {
      "date": "2026-11-06",
      "type": "OPERATING",
      "closingTime": "2026-11-06T22:00:00-05:00",
      "openingTime": "2026-11-06T09:00:00-05:00"
    },
    {
      "date": "2026-11-07",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-11-07T09:00:00-05:00",
      "description": "Early Entry",
      "openingTime": "2026-11-07T08:30:00-05:00"
    },
    {
      "date": "2026-11-07",
      "type": "OPERATING",
      "closingTime": "2026-11-07T22:00:00-05:00",
      "openingTime": "2026-11-07T09:00:00-05:00"
    },
    {
      "date": "2026-11-08",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-11-08T09:00:00-05:00",
      "description": "Early Entry",
      "openingTime": "2026-11-08T08:30:00-05:00"
    },
    {
      "date": "2026-11-08",
      "type": "OPERATING",
      "closingTime": "2026-11-08T18:00:00-05:00",
      "openingTime": "2026-11-08T09:00:00-05:00"
    },
    {
      "date": "2026-11-08",
      "type": "TICKETED_EVENT",
      "closingTime": "2026-11-09T00:00:00-05:00",
      "description": "Special Ticketed Event",
      "openingTime": "2026-11-08T19:00:00-05:00"
    }
  ]
}