"""Specifies cases/kiosk_units/verdict.py (#206, step 4 of #202; "Ruling after the e5b3fd0 job" in
~/.claude/plans/202/step4/brief.md): `data.mount` is not a unit file anywhere in this layer -- it is
produced at boot by systemd's fstab generator from `/etc/fstab` (confirmed on bench, read-only:
`systemctl cat data.mount` prints `# Automatically generated by systemd-fstab-generator`;
`systemctl is-active data.mount` answers `active`; `findmnt /data` shows it mounted). `systemd-
analyze verify` on the board never sees a generated unit, with or without `--generators=yes`
(tried at e5b3fd0, same "Unit data.mount not found" -- the flag is gone from case.py). Four shipped
units `Requires=`/`After=` `data.mount` and all report the same line.

`verdict(verify_output, active_units)` replaces the former `systemd_analyze_verdict(returncode,
stderr_text)`: case.py collects every "Unit X not found" name verify_output reports and asks the
board `systemctl is-active X` for each, handing the answer map here. A "Unit X not found" line is
excused -- not a defect -- exactly when active_units[X] == "active"; every other line, and a
not-found line whose name answers anything else (or is absent from active_units, meaning case.py
never asked), survives into the verdict. "ok" iff nothing survives; "error" naming whatever does,
verbatim.

One parametrized test, one row per code branch: empty/blank-only output is "ok"; a lone excused
not-found line is "ok"; a not-found line the board does NOT confirm active is "error"; a not-found
line for a name case.py never queried is "error"; an unrelated defect line (no "not found" pattern
at all) is "error" regardless of active_units; several excused not-found lines together are still
"ok" (the real four-shipped-units shape); an excused not-found line alongside a genuine unrelated
line is "error" naming only the unrelated line, not the excused one.

Grounded on this session's own read-only bench recon (`local/202/step4/acceptance/` scripts, this
repository's real units) and the real pipeline failure text quoted in the lead's own ruling:
- `"kiosk.service: Failed to create kiosk.service/start: Unit data.mount not found."` -- the real
  line from the `e5b3fd0` pipeline job's own failure (`kiosk-provision.service` reported the
  identical shape for the same reason, per the ruling).
- `"kiosk.service: Service has no ExecStart=, ExecStop=, or SuccessAction=. Refusing."` and
  `"Unit kiosk.service has a bad unit file setting."` -- the real genuine-defect lines measured
  directly against this host's own systemd in an earlier round (impl-notes.md "Round 2"), carrying
  no "Unit ... not found" shape at all, so they survive regardless of active_units.
"""

import pytest

from oeqa.runtime.cases.kiosk_units.verdict import verdict

# The real line from the e5b3fd0 pipeline job's own kiosk.service failure (see module docstring).
KIOSK_DATA_MOUNT_NOT_FOUND = "kiosk.service: Failed to create kiosk.service/start: Unit data.mount not found."
PROVISION_DATA_MOUNT_NOT_FOUND = "kiosk-provision.service: Failed to create kiosk-provision.service/start: Unit data.mount not found."

# A real genuine defect, carrying no "Unit ... not found" shape -- measured directly against this
# host's own systemd in an earlier round (see module docstring).
EXECSTART_MISSING = (
    "kiosk.service: Service has no ExecStart=, ExecStop=, or SuccessAction=. Refusing.; "
    "Unit kiosk.service has a bad unit file setting."
)


@pytest.mark.parametrize(
    ("name", "verify_output", "active_units", "want_outcome", "want_reason_contains"),
    [
        ("clean verify, no output at all", "", {}, "ok", ()),
        ("output present but only blank lines", "\n  \n", {}, "ok", ()),
        (
            "one not-found line, the board confirms it active, excused",
            KIOSK_DATA_MOUNT_NOT_FOUND,
            {"data.mount": "active"},
            "ok",
            (),
        ),
        (
            "one not-found line, the board answers anything else, not excused",
            KIOSK_DATA_MOUNT_NOT_FOUND,
            {"data.mount": "inactive"},
            "error",
            ("data.mount",),
        ),
        (
            "one not-found line for a name case.py never queried, not excused",
            KIOSK_DATA_MOUNT_NOT_FOUND,
            {},
            "error",
            ("data.mount",),
        ),
        (
            "a genuine defect carrying no not-found shape survives regardless of active_units",
            EXECSTART_MISSING,
            {"data.mount": "active"},
            "error",
            ("Refusing", "bad unit file setting"),
        ),
        (
            "several excused not-found lines together, still ok -- the real four-unit shape",
            KIOSK_DATA_MOUNT_NOT_FOUND + "\n" + PROVISION_DATA_MOUNT_NOT_FOUND,
            {"data.mount": "active"},
            "ok",
            (),
        ),
        (
            "an excused not-found line alongside a genuine unrelated line names only the latter",
            KIOSK_DATA_MOUNT_NOT_FOUND + "\n" + EXECSTART_MISSING,
            {"data.mount": "active"},
            "error",
            ("Refusing",),
        ),
    ],
)
def test_verdict_outcome(name, verify_output, active_units, want_outcome, want_reason_contains):
    outcome, reason = verdict(verify_output, active_units)
    assert outcome == want_outcome, f"{name}: {reason!r}"
    for token in want_reason_contains:
        assert token in reason, f"{name}: {token!r} not in {reason!r}"


def test_verdict_excused_line_does_not_appear_in_error_reason():
    # The one branch whose contract is specifically EXCLUSION, not just presence of the real
    # defect -- not expressible as a plain "contains" row above, so it keeps its own test.
    outcome, reason = verdict(
        KIOSK_DATA_MOUNT_NOT_FOUND + "\n" + EXECSTART_MISSING, {"data.mount": "active"})
    assert outcome == "error"
    assert "data.mount" not in reason
