SUMMARY = "Node.js (upstream binary, build host only)"
DESCRIPTION = "The frontend bundle is generated by vite, which runs on node. Node is a BUILD-HOST \
tool here and never reaches the device: upstream dropped ARMv6 after v12, and the kiosk serves \
static files. meta-openembedded ships nodejs 20.20.2 against the app's declared 26, and building \
node from source costs an hour to produce a compiler for HTML -- so this unpacks the official \
tarball the way poky's go-binary-native does, and is a native recipe only."
HOMEPAGE = "https://nodejs.org/"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=91714ce137cce8ffea829e50d3341205"

# No PROVIDES = "nodejs-native": meta-oe already provides it, and a second
# provider needs a PREFERRED_PROVIDER. Consumers name this recipe in DEPENDS.

# Upstream names the arch x64/arm64 where Yocto says x86_64/aarch64. An unlisted
# host falls through to its own name, which has no checksum below.
def node_build_arch(d):
    arch = d.getVar("BUILD_ARCH")
    return {"x86_64": "x64", "aarch64": "arm64"}.get(arch, arch)

NODE_BUILD_ARCH = "${@node_build_arch(d)}"

# Checksums at https://nodejs.org/dist/v${PV}/SHASUMS256.txt
SRC_URI = "https://nodejs.org/dist/v${PV}/node-v${PV}-linux-${NODE_BUILD_ARCH}.tar.xz;name=linux_${NODE_BUILD_ARCH}"
SRC_URI[linux_x64.sha256sum] = "ca70e9e349de048b9522abb3adc05b3bd6f43c5ffd3ec57916c7da292f59f022"
SRC_URI[linux_arm64.sha256sum] = "7a6353f63eb3d04765004b4adf172616243e4522434635cb1d26288658b04ab5"

# Held to the major the app's engines field declares.
UPSTREAM_CHECK_URI = "https://nodejs.org/dist/"
UPSTREAM_CHECK_REGEX = "v(?P<pver>26(\.\d+)+)/"

CVE_PRODUCT = "nodejs:node.js"

S = "${WORKDIR}/node-v${PV}-linux-${NODE_BUILD_ARCH}"

inherit native

do_compile() {
    :
}

# The tarball is already laid out as a prefix, and bin/npm and bin/npx are
# relative symlinks into lib/node_modules; copying wholesale keeps them
# resolving.
do_install() {
    install -d ${D}${prefix}
    cp --preserve=mode,timestamps -R ${S}/bin ${S}/include ${S}/lib ${S}/share ${D}${prefix}/
}
