#!/usr/bin/env python3
"""Generate the checksummed Go module closure oapi-codegen needs at build time.

    go-mods.py -- write wisekiosk-backend-go-mods.inc (gitignored, build input)

Clones the pinned WiseKiosk commit and runs `go list -deps` against the
codegen tool's own import path to populate a scratch GOMODCACHE with exactly
the modules it needs, then renders one SRC_URI pair per file the proxy
served. See meta-wisekiosk/recipes-wisekiosk/wisekiosk/README.md.

`render_inc` is the importable seam tools/go-mods-test.py drives directly, on
a fabricated cache -- no clone, no network, no real `go`. `fetch_cache` is the
only function that touches either.
"""
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parent

# Where the pin and the git URL come from -- one file, shared with
# wisekiosk-frontend_git.bb and wisekiosk-backend_git.bb.
SRC_INC = ROOT / "meta-wisekiosk/recipes-wisekiosk/wisekiosk/wisekiosk-src.inc"

# Written at build entry (Justfile, right after tools/write-build-rev.sh) and
# gitignored -- never committed (owner, 2026-09-27: nothing autogenerable is).
INC_PATH = ROOT / "meta-wisekiosk/recipes-wisekiosk/wisekiosk/wisekiosk-backend-go-mods.inc"

# The one binary the codegen module closure exists to build. `go list -deps`
# on THIS import path, not the app's, is what surfaces every module
# oapi-codegen needs -- tool-only dependencies included.
CODEGEN_TOOL = "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen"

# Forced regardless of host Go environment, for a byte-identical .inc across
# dev hosts. -modcacherw so the scratch GOMODCACHE fetch_cache() creates can
# be removed afterwards -- Go writes it read-only otherwise. GOWORK=off so a
# host go.work cannot change module resolution the rest of this dict pins.
GO_ENV = {
    "GOPROXY": "https://proxy.golang.org",
    "GOSUMDB": "sum.golang.org",
    "GOFLAGS": "-modcacherw",
    "GOENV": "off",
    "GOWORK": "off",
    "GOTOOLCHAIN": "local",
    "GOOS": "linux",
    "GOARCH": "amd64",
    "GOPRIVATE": "",
    "GONOPROXY": "",
    "GONOSUMDB": "",
}

HEADER = "# Generated by tools/go-mods.py from WiseKiosk {srcrev}; do not edit, do not commit."

# git's own canonical list of repo-local vars. A pre-commit hook in a linked
# worktree exports GIT_DIR/GIT_INDEX_FILE (absolute paths into that worktree's
# gitdir) to this process, and a `git clone`/`checkout` below that inherited
# them would act on the real repo instead of the scratch clone -- the same
# leak tools/cve-tools-test.py's clean_env() strips.
GIT_LOCAL_VARS = frozenset(subprocess.run(
    ["git", "rev-parse", "--local-env-vars"],
    capture_output=True, text=True, check=True).stdout.split())


def clean_env(**extra):
    env = {k: v for k, v in os.environ.items() if k not in GIT_LOCAL_VARS}
    env.update(extra)
    return env


# Workdirs fetch_cache() has created and not yet removed. Empty unless the
# real fetch_cache ran -- a test that replaces fetch_cache with a fixture
# never touches this, so _cleanup_workdirs() is a safe no-op there.
_LEFTOVER_WORKDIRS = []


def _cleanup_workdirs():
    while _LEFTOVER_WORKDIRS:
        shutil.rmtree(_LEFTOVER_WORKDIRS.pop(), ignore_errors=True)


def refuse(message: str) -> int:
    print(f"{message} -- refusing to report a pass", file=sys.stderr)
    return 2


def _src_inc_fields():
    """(url, srcrev) as bitbake reads them from wisekiosk-src.inc."""
    text = SRC_INC.read_text()
    srcrev = re.search(r'^SRCREV\s*=\s*"([0-9a-f]{40})"', text, re.M).group(1)
    src_uri = re.search(r'^SRC_URI\s*=\s*"([^"]+)"', text, re.M).group(1)
    scheme_and_path, *params = src_uri.split(";")
    protocol = next((p.split("=", 1)[1] for p in params
                      if p.startswith("protocol=")), None)
    _, _, rest = scheme_and_path.partition("://")
    return f"{protocol or 'https'}://{rest}", srcrev


def _escaped_modules(cache_dir: Path):
    """(escaped, version, ext, file) for every zip/mod file `go mod download`
    left under cache_dir. `escaped` is read off the directory names as-is --
    Go's own on-disk escaping (an uppercase letter as `!` + its lower-case
    form), not re-derived here."""
    download = Path(cache_dir) / "cache" / "download"
    if not download.is_dir():
        return
    for at_v in download.rglob("@v"):
        if not at_v.is_dir():
            continue
        escaped = at_v.parent.relative_to(download).as_posix()
        for f in at_v.iterdir():
            if f.suffix in (".zip", ".mod"):
                yield escaped, f.stem, f.suffix[1:], f


def render_inc(cache_dir: Path, srcrev: str) -> str:
    order = {"zip": 0, "mod": 1}
    entries = sorted(_escaped_modules(cache_dir),
                     key=lambda e: (e[0], e[1], order[e[2]]))

    lines = [HEADER.format(srcrev=srcrev), "",
             f'WISEKIOSK_GOMODS_SRCREV = "{srcrev}"', ""]
    for escaped, version, ext, path in entries:
        digest = hashlib.sha256(f"{escaped}@{version}.{ext}".encode()).hexdigest()
        ident = f"gomod_{digest[:16]}"
        sha256hex = hashlib.sha256(path.read_bytes()).hexdigest()
        url = f"https://proxy.golang.org/{escaped}/@v/{version}.{ext}"
        downloadfilename = f"gomod/{escaped}/@v/{version}.{ext}"
        subdir = f"goproxy/{escaped}/@v"
        lines.append(
            f'SRC_URI += "{url};downloadfilename={downloadfilename};'
            f'subdir={subdir};unpack=0;name={ident}"')
        lines.append(f'SRC_URI[{ident}.sha256sum] = "{sha256hex}"')
    return "\n".join(lines) + "\n"


def _go_version_tuple(text: str):
    m = re.search(r"go(\d+)\.(\d+)(?:\.(\d+))?", text)
    return tuple(int(x or 0) for x in m.groups())


def _required_go_version(repo: Path):
    """The `go` directive backend/go.mod declares, e.g. `go 1.24.0` -> (1, 24, 0)."""
    text = (repo / "backend" / "go.mod").read_text()
    m = re.search(r"^go\s+(\d+)\.(\d+)(?:\.(\d+))?", text, re.M)
    return tuple(int(x or 0) for x in m.groups())


def current_srcrev(inc_path: Path = INC_PATH):
    """The WISEKIOSK_GOMODS_SRCREV inc_path already records, or None if the
    file is missing or carries none. The importable seam for "is this .inc
    already current" -- tests drive it directly, on a fixture path."""
    if not Path(inc_path).exists():
        return None
    m = re.search(r'^WISEKIOSK_GOMODS_SRCREV\s*=\s*"([0-9a-f]{40})"',
                  Path(inc_path).read_text(), re.M)
    return m.group(1) if m else None


def fetch_cache(url: str, srcrev: str) -> Path:
    """Clone the pinned commit and run the one Go command that touches the
    network: `go list -deps` against oapi-codegen's own import path, which
    downloads exactly the modules it needs into a scratch GOMODCACHE."""
    have = _go_version_tuple(subprocess.run(
        ["go", "version"], capture_output=True, text=True, check=True).stdout)

    workdir = Path(tempfile.mkdtemp(prefix="go-mods-"))
    _LEFTOVER_WORKDIRS.append(workdir)
    repo = workdir / "repo"
    subprocess.run(["git", "clone", "--quiet", url, str(repo)], check=True,
                   env=clean_env())
    subprocess.run(["git", "-C", str(repo), "checkout", "--quiet", srcrev],
                   check=True, env=clean_env())

    need = _required_go_version(repo)
    if have < need:
        sys.exit(refuse(
            f"host go {'.'.join(map(str, have))} is older than the app's "
            f"go.mod ({'.'.join(map(str, need))})"))

    gomodcache = workdir / "gomodcache"
    gomodcache.mkdir()
    env = clean_env(**GO_ENV, GOMODCACHE=str(gomodcache))
    subprocess.run(["go", "list", "-json=Dir,Module", "-deps", CODEGEN_TOOL],
                   cwd=repo / "backend", env=env, check=True,
                   stdout=subprocess.DEVNULL)
    return gomodcache


def main() -> int:
    if sys.argv[1:]:
        print(__doc__.strip().split("\n\n")[1], file=sys.stderr)
        return 2

    url, srcrev = _src_inc_fields()
    if current_srcrev(INC_PATH) == srcrev:
        return 0

    try:
        cache_dir = fetch_cache(url, srcrev)
        rendered = render_inc(cache_dir, srcrev)
    finally:
        _cleanup_workdirs()

    INC_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = INC_PATH.with_suffix(INC_PATH.suffix + ".tmp")
    tmp.write_text(rendered)
    try:
        os.replace(tmp, INC_PATH)
    except OSError:
        tmp.unlink(missing_ok=True)
        raise
    return 0


if __name__ == "__main__":
    sys.exit(main())
