#!/usr/bin/env python3
"""Generate the checksummed Go module closure oapi-codegen needs at build time.

    go-mods.py            -- regenerate wisekiosk-backend-go-mods.inc
    go-mods.py --check    -- regenerate to a temp file and diff it against the
                              committed one; exit 1 on drift

`go tool oapi-codegen` is a build-time-only dependency of wisekiosk-backend: it
never reaches the shipped binary, but `go build` in wisekiosk-backend_git.bb
runs GOPROXY=off, so its module graph has to arrive as checksummed SRC_URI
entries rather than a live fetch. This clones the pinned WiseKiosk commit,
runs `go list -deps` against the codegen tool's own import path to populate a
scratch GOMODCACHE with exactly the modules it needs, and renders one SRC_URI
pair per file the proxy served.

`render_inc` is the importable seam tools/go-mods-test.py drives directly, on
a fabricated cache -- no clone, no network, no real `go`. `fetch_cache` is the
only function that touches either; `check` composes the two against INC_PATH
the same way this script's own CLI does.
"""
import difflib
import hashlib
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parent

# Where the pin and the git URL come from -- one file, shared with
# wisekiosk-frontend_git.bb and wisekiosk-backend_git.bb.
SRC_INC = ROOT / "meta-wisekiosk/recipes-wisekiosk/wisekiosk/wisekiosk-src.inc"

# The committed output. Its own first line names the SRCREV it was rendered
# from, so a stale file is visible in `git diff` without running --check.
INC_PATH = ROOT / "meta-wisekiosk/recipes-wisekiosk/wisekiosk/wisekiosk-backend-go-mods.inc"

# The one binary the codegen module closure exists to build. `go list -deps`
# on THIS import path, not the app's, is what surfaces every module
# oapi-codegen needs -- tool-only dependencies included.
CODEGEN_TOOL = "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen"

# Forced regardless of the host's own Go environment, so the rendered .inc is
# identical on any dev host: GOOS/GOARCH pinned because Go modules are
# whole-module downloads (host arch never changes which modules a build
# needs); GOPROXY/GOSUMDB pinned to the public defaults so a host's own proxy
# config can't change what gets fetched; GOFLAGS/GOENV/GOPRIVATE/GONOPROXY/
# GONOSUMDB cleared so no host dotfile or environment leaks in.
GO_ENV = {
    "GOPROXY": "https://proxy.golang.org",
    "GOSUMDB": "sum.golang.org",
    "GOFLAGS": "",
    "GOENV": "off",
    "GOTOOLCHAIN": "local",
    "GOOS": "linux",
    "GOARCH": "amd64",
    "GOPRIVATE": "",
    "GONOPROXY": "",
    "GONOSUMDB": "",
}

HEADER = "# Generated by tools/go-mods.py from WiseKiosk {srcrev}; do not edit."


def refuse(message: str) -> int:
    print(f"{message} -- refusing to report a pass", file=sys.stderr)
    return 2


def _src_inc_fields():
    """(url, srcrev) as bitbake reads them from wisekiosk-src.inc."""
    text = SRC_INC.read_text()
    srcrev = re.search(r'^SRCREV\s*=\s*"([0-9a-f]{40})"', text, re.M).group(1)
    src_uri = re.search(r'^SRC_URI\s*=\s*"([^"]+)"', text, re.M).group(1)
    scheme_and_path, *params = src_uri.split(";")
    protocol = next((p.split("=", 1)[1] for p in params
                      if p.startswith("protocol=")), None)
    _, _, rest = scheme_and_path.partition("://")
    return f"{protocol or 'https'}://{rest}", srcrev


def _escaped_modules(cache_dir: Path):
    """(escaped, version, ext, file) for every zip/mod file `go mod download`
    left under cache_dir. `escaped` is read off the directory names as-is --
    Go's own on-disk escaping (an uppercase letter as `!` + its lower-case
    form), not re-derived here."""
    download = Path(cache_dir) / "cache" / "download"
    if not download.is_dir():
        return
    for at_v in download.rglob("@v"):
        if not at_v.is_dir():
            continue
        escaped = at_v.parent.relative_to(download).as_posix()
        for f in at_v.iterdir():
            if f.suffix in (".zip", ".mod"):
                yield escaped, f.stem, f.suffix[1:], f


def render_inc(cache_dir: Path, srcrev: str) -> str:
    order = {"zip": 0, "mod": 1}
    entries = sorted(_escaped_modules(cache_dir),
                     key=lambda e: (e[0], e[1], order[e[2]]))

    lines = [HEADER.format(srcrev=srcrev), ""]
    for escaped, version, ext, path in entries:
        digest = hashlib.sha256(f"{escaped}@{version}.{ext}".encode()).hexdigest()
        ident = f"gomod_{digest[:16]}"
        sha256hex = hashlib.sha256(path.read_bytes()).hexdigest()
        url = f"https://proxy.golang.org/{escaped}/@v/{version}.{ext}"
        downloadfilename = f"gomod/{escaped}/@v/{version}.{ext}"
        subdir = f"goproxy/{escaped}/@v"
        lines.append(
            f'SRC_URI += "{url};downloadfilename={downloadfilename};'
            f'subdir={subdir};unpack=0;name={ident}"')
        lines.append(f'SRC_URI[{ident}.sha256sum] = "{sha256hex}"')
    return "\n".join(lines) + "\n"


def _go_version_tuple(text: str):
    m = re.search(r"go(\d+)\.(\d+)(?:\.(\d+))?", text)
    return tuple(int(x or 0) for x in m.groups())


def _required_go_version(repo: Path):
    """The `go` directive backend/go.mod declares, e.g. `go 1.24.0` -> (1, 24, 0)."""
    text = (repo / "backend" / "go.mod").read_text()
    m = re.search(r"^go\s+(\d+)\.(\d+)(?:\.(\d+))?", text, re.M)
    return tuple(int(x or 0) for x in m.groups())


def fetch_cache(url: str, srcrev: str) -> Path:
    """Clone the pinned commit and run the one Go command that touches the
    network: `go list -deps` against oapi-codegen's own import path, which
    downloads exactly the modules it needs into a scratch GOMODCACHE."""
    have = _go_version_tuple(subprocess.run(
        ["go", "version"], capture_output=True, text=True, check=True).stdout)

    workdir = Path(tempfile.mkdtemp(prefix="go-mods-"))
    repo = workdir / "repo"
    subprocess.run(["git", "clone", "--quiet", url, str(repo)], check=True)
    subprocess.run(["git", "-C", str(repo), "checkout", "--quiet", srcrev],
                   check=True)

    need = _required_go_version(repo)
    if have < need:
        sys.exit(refuse(
            f"host go {'.'.join(map(str, have))} is older than the app's "
            f"go.mod ({'.'.join(map(str, need))})"))

    gomodcache = workdir / "gomodcache"
    gomodcache.mkdir()
    env = {**os.environ, **GO_ENV, "GOMODCACHE": str(gomodcache)}
    subprocess.run(["go", "list", "-json=Dir,Module", "-deps", CODEGEN_TOOL],
                   cwd=repo / "backend", env=env, check=True,
                   stdout=subprocess.DEVNULL)
    return gomodcache


def check(url: str, srcrev: str, show_diff: bool = False) -> int:
    """render_inc(fetch_cache(url, srcrev), srcrev), compared against
    INC_PATH's committed content. Both names are looked up on this module at
    call time, so a test can replace either -- the same pattern
    cve-tools-test.py uses for layer-currency.py's check()."""
    cache_dir = fetch_cache(url, srcrev)
    current = render_inc(cache_dir, srcrev)
    committed = INC_PATH.read_text() if INC_PATH.exists() else ""
    if current == committed:
        return 0
    if show_diff:
        sys.stdout.writelines(difflib.unified_diff(
            committed.splitlines(keepends=True),
            current.splitlines(keepends=True),
            fromfile=str(INC_PATH), tofile="regenerated"))
    return 1


def main() -> int:
    argv = sys.argv[1:]
    if argv not in ([], ["--check"]):
        print(__doc__.strip().split("\n\n")[1], file=sys.stderr)
        return 2

    url, srcrev = _src_inc_fields()
    if argv == ["--check"]:
        return check(url, srcrev, show_diff=True)

    cache_dir = fetch_cache(url, srcrev)
    INC_PATH.write_text(render_inc(cache_dir, srcrev))
    return 0


if __name__ == "__main__":
    sys.exit(main())
