#!/usr/bin/env python3
"""Self-test for tools/go-mods.py's rendering seam. Run by `just guards` and by CI.

    go-mods-test.py             -- every case

`render_inc(cache_dir, srcrev)` is the importable seam: it walks a GOMODCACHE
laid out exactly as `go mod download` leaves one (`cache/download/<escaped
module path>/@v/<version>.{zip,mod,...}`) and renders the recipe include. Every
fixture here IS such a cache, fabricated small enough to read -- never a real
`go list`/clone, which needs network the guard must not depend on.

The escaped path segments below reuse Go's own on-disk escaping (an uppercase
letter becomes `!` + its lower-case form): the walk reads directory names
as-is off disk, so a fixture with a literal `!x` segment is what an uppercase
module path actually looks like in GOMODCACHE, not a re-implementation of the
escaping rule.
"""
import contextlib
import hashlib
import importlib.util
import io
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from types import SimpleNamespace

TOOLS = Path(__file__).resolve().parent
sys.dont_write_bytecode = True


def load(name):
    spec = importlib.util.spec_from_file_location(
        name.replace("-", "_"), TOOLS / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


go_mods = load("go-mods")

PASS, FAIL = [], []


def case(name, got, want):
    (PASS if got == want else FAIL).append(name)
    if got != want:
        print(f"FAIL  {name}\n        want {want!r}\n        got  {got!r}")


SRCREV = "1becdf0dd12943bc7f98d6d52a76494bef02fb1f"


def seed(gomodcache, escaped, version, ext, content):
    """One file at the exact path `go mod download` would leave it."""
    p = Path(gomodcache) / "cache" / "download" / escaped / "@v" / f"{version}.{ext}"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_bytes(content)
    return p


def entry_id(escaped, version, ext):
    digest = hashlib.sha256(f"{escaped}@{version}.{ext}".encode()).hexdigest()
    return f"gomod_{digest[:16]}"


def entry_lines(escaped, version, ext, sha256hex):
    """The exact two-line SRC_URI pair the plan specifies for one file."""
    ident = entry_id(escaped, version, ext)
    url = f"https://proxy.golang.org/{escaped}/@v/{version}.{ext}"
    downloadfilename = f"gomod/{escaped}/@v/{version}.{ext}"
    subdir = f"goproxy/{escaped}/@v"
    return [
        f'SRC_URI += "{url};downloadfilename={downloadfilename};'
        f'subdir={subdir};unpack=0;name={ident}"',
        f'SRC_URI[{ident}.sha256sum] = "{sha256hex}"',
    ]


def src_uri_lines(rendered):
    """Only the SRC_URI body lines, in order -- independent of whatever
    blank-line or comment layout the generator puts around them, which the
    plan does not specify."""
    return [ln for ln in rendered.splitlines() if ln.startswith("SRC_URI")]


def header_cases():
    with tempfile.TemporaryDirectory() as tmp:
        seed(tmp, "example.com/a", "v1.0.0", "zip", b"zip-bytes")
        seed(tmp, "example.com/a", "v1.0.0", "mod", b"mod-bytes")
        rendered = go_mods.render_inc(Path(tmp), SRCREV)
    case("render_inc: first line is the exact generated-by header",
         rendered.splitlines()[0],
         f"# Generated by tools/go-mods.py from WiseKiosk {SRCREV}; "
         "do not edit, do not commit.")
    case("render_inc: names the srcrev it was rendered from",
         rendered.splitlines()[2],
         f'WISEKIOSK_GOMODS_SRCREV = "{SRCREV}"')


def entry_shape_cases():
    """One module, one version, both files: the exact SRC_URI entry form,
    the id derivation, and that sha256 is taken over the real fixture bytes."""
    zip_bytes = b"a fixture zip payload, not a real Go module"
    mod_bytes = b"module example.com/a\n\ngo 1.24\n"
    with tempfile.TemporaryDirectory() as tmp:
        seed(tmp, "example.com/a", "v1.0.0", "zip", zip_bytes)
        seed(tmp, "example.com/a", "v1.0.0", "mod", mod_bytes)
        lines = src_uri_lines(go_mods.render_inc(Path(tmp), SRCREV))

    want = (
        entry_lines("example.com/a", "v1.0.0", "zip",
                    hashlib.sha256(zip_bytes).hexdigest())
        + entry_lines("example.com/a", "v1.0.0", "mod",
                      hashlib.sha256(mod_bytes).hexdigest())
    )
    case("render_inc: zip-then-mod, exact SRC_URI entry form and sha256",
         lines, want)


def mod_only_cases():
    """A version with a .mod but no .zip (a module used only for its go.mod,
    e.g. a transitive dependency of the build list) emits the .mod alone."""
    mod_bytes = b"module example.com/modonly\n\ngo 1.24\n"
    with tempfile.TemporaryDirectory() as tmp:
        seed(tmp, "example.com/modonly", "v0.1.0", "mod", mod_bytes)
        lines = src_uri_lines(go_mods.render_inc(Path(tmp), SRCREV))

    case("render_inc: a mod-only version emits exactly one SRC_URI pair",
         len(lines), 2)
    case("render_inc: a mod-only version emits only the .mod entry",
         lines,
         entry_lines("example.com/modonly", "v0.1.0", "mod",
                     hashlib.sha256(mod_bytes).hexdigest()))


def escaping_and_sort_cases():
    """Four modules seeded out of order, one with an uppercase-escaped
    segment and one with two versions -- render_inc must sort by escaped
    path then version, and preserve the escaped segment verbatim (it is
    already how Go's own cache spells an uppercase path, not something
    render_inc re-derives)."""
    files = {
        ("example.com/b", "v1.0.0", "zip"): b"b-zip",
        ("example.com/b", "v1.0.0", "mod"): b"b-mod",
        ("example.com/!x", "v1.0.0", "zip"): b"bangx-zip",
        ("example.com/!x", "v1.0.0", "mod"): b"bangx-mod",
        ("example.com/a", "v2.0.0", "mod"): b"a-v2-mod",
        ("example.com/a", "v1.0.0", "zip"): b"a-v1-zip",
        ("example.com/a", "v1.0.0", "mod"): b"a-v1-mod",
    }
    # Seeded in an order that is neither sorted-by-path nor sorted-by-version,
    # so a generator that merely preserves filesystem walk order would not
    # accidentally pass this.
    order = [
        ("example.com/b", "v1.0.0", "zip"),
        ("example.com/a", "v2.0.0", "mod"),
        ("example.com/!x", "v1.0.0", "mod"),
        ("example.com/a", "v1.0.0", "zip"),
        ("example.com/!x", "v1.0.0", "zip"),
        ("example.com/a", "v1.0.0", "mod"),
        ("example.com/b", "v1.0.0", "mod"),
    ]
    with tempfile.TemporaryDirectory() as tmp:
        for key in order:
            escaped, version, ext = key
            seed(tmp, escaped, version, ext, files[key])
        lines = src_uri_lines(go_mods.render_inc(Path(tmp), SRCREV))

    want = []
    for escaped, version, ext in (
        ("example.com/!x", "v1.0.0", "zip"),
        ("example.com/!x", "v1.0.0", "mod"),
        ("example.com/a", "v1.0.0", "zip"),
        ("example.com/a", "v1.0.0", "mod"),
        ("example.com/a", "v2.0.0", "mod"),
        ("example.com/b", "v1.0.0", "zip"),
        ("example.com/b", "v1.0.0", "mod"),
    ):
        want += entry_lines(escaped, version, ext,
                             hashlib.sha256(files[(escaped, version, ext)])
                             .hexdigest())

    case("render_inc: sorted by case-escaped path then version, "
         "zip before mod, uppercase escaping preserved verbatim",
         lines, want)


# --- go-version contract (W3): fetch_cache refuses a too-old host `go` -----
#
# `_go_version_tuple` and `_required_go_version` are the two parsing seams;
# `fetch_cache`'s `have < need` comparison between them is the refusal path
# itself. `fetch_cache` also clones and runs `go list`, so exercising the
# comparison end-to-end monkeypatches `subprocess.run` -- there is no wrapper
# function to stub instead, the way layer-currency.py's `git()` gives
# cve-tools-test.py one.

GO_MOD_1260 = "module example.com/fixture\n\ngo 1.26.0\n"
GO_MOD_1260_SHORT = "module example.com/fixture\n\ngo 1.26\n"


def version_tuple_cases():
    case("_go_version_tuple: exact three-component `go version` output",
         go_mods._go_version_tuple("go version go1.26.0 linux/amd64\n"),
         (1, 26, 0))
    # Spelled differently but valid: a newer patch must not be misread as
    # equal -- the comparison is a tuple compare, not a string compare.
    case("_go_version_tuple: a newer patch parses strictly greater",
         go_mods._go_version_tuple("go version go1.26.1 linux/amd64\n") >
         go_mods._go_version_tuple("go version go1.26.0 linux/amd64\n"),
         True)
    case("_go_version_tuple: an older minor parses strictly less",
         go_mods._go_version_tuple("go version go1.25.9 linux/amd64\n") <
         go_mods._go_version_tuple("go version go1.26.0 linux/amd64\n"),
         True)
    # `go version` never emits a bare two-component string, but the regex's
    # patch group is optional -- missing reads as 0, not refused outright.
    case("_go_version_tuple: a two-component version fills patch with 0",
         go_mods._go_version_tuple("go version go1.26 linux/amd64\n"),
         (1, 26, 0))
    # A devel/rc build string: the regex has no dedicated case for it, so it
    # reads whatever `go\d+\.\d+` it finds first -- here the base series
    # `go1.24` embedded in the devel build stamp, silently dropping the
    # `-e705a...` commit suffix. This is the parser's actual behaviour, not a
    # claimed feature: a devel toolchain built off an older series is (only
    # coincidentally correctly) read as behind; one built off the SAME series
    # as a later release would read as behind too, wrongly.
    case("_go_version_tuple: a devel build string reads its embedded series",
         go_mods._go_version_tuple(
             "go version devel go1.24-e705a02574 Tue Sep 26 15:22:01 2023 "
             "+0000 linux/amd64\n"),
         (1, 24, 0))


def required_go_version_cases():
    with tempfile.TemporaryDirectory() as tmp:
        repo = Path(tmp)
        (repo / "backend").mkdir()
        (repo / "backend" / "go.mod").write_text(GO_MOD_1260)
        case("_required_go_version: three-component `go` directive",
             go_mods._required_go_version(repo), (1, 26, 0))

    with tempfile.TemporaryDirectory() as tmp:
        repo = Path(tmp)
        (repo / "backend").mkdir()
        (repo / "backend" / "go.mod").write_text(GO_MOD_1260_SHORT)
        case("_required_go_version: two-component `go` directive fills "
             "patch with 0",
             go_mods._required_go_version(repo), (1, 26, 0))


class FakeToolchain:
    """Stands in for the four subprocess.run calls fetch_cache makes -- `go
    version`, `git clone`, `git checkout` and `go list` -- around its version
    gate. Recording whether `go list` ran is what proves a refusal
    short-circuited rather than merely printing a message and continuing.

    `go list`'s fake stdout defaults to naming DEFAULT_MODULE alone, and the
    default seed puts that module's .zip in the fake GOMODCACHE -- a real
    `go list -deps` run always includes the codegen tool's own module, and
    fetch_cache refuses outright if it doesn't, so this is the toolchain's
    "trusted, complete" baseline. Tests exercising the codegen-tool-presence
    or completeness checks themselves pass go_list_stdout/seed_gomodcache."""

    DEFAULT_MODULE = ("github.com/oapi-codegen/oapi-codegen/v2", "v2.4.1")

    def __init__(self, go_version_stdout, go_mod_text, go_list_stdout=None,
                 seed_gomodcache=None):
        self.go_version_stdout = go_version_stdout
        self.go_mod_text = go_mod_text
        self.go_list_stdout = (go_list_stdout if go_list_stdout is not None
                               else self._default_deps_stream())
        self.seed_gomodcache = (seed_gomodcache if seed_gomodcache is not None
                                else self._seed_default_module)
        self.go_list_called = False
        self.go_list_env = None
        self.workdir = None

    def _default_deps_stream(self):
        path, version = self.DEFAULT_MODULE
        return json.dumps({"Dir": "/x",
                           "Module": {"Path": path, "Version": version}})

    def _seed_default_module(self, gomodcache):
        path, version = self.DEFAULT_MODULE
        seed(gomodcache, path, version, "zip", b"fixture zip payload")

    def __call__(self, argv, **kwargs):
        if argv[:2] == ["go", "version"]:
            return SimpleNamespace(stdout=self.go_version_stdout, returncode=0)
        if argv[:2] == ["git", "clone"]:
            repo = Path(argv[-1])
            self.workdir = repo.parent
            (repo / "backend").mkdir(parents=True)
            (repo / "backend" / "go.mod").write_text(self.go_mod_text)
            return SimpleNamespace(returncode=0)
        if argv[:2] == ["git", "-C"] and "checkout" in argv:
            return SimpleNamespace(returncode=0)
        if argv[:2] == ["go", "list"]:
            self.go_list_called = True
            self.go_list_env = kwargs.get("env")
            # fetch_cache has already created workdir/gomodcache for real by
            # this point (subprocess.run is the only thing faked) -- seeding
            # it here, just before "go list" returns, is what lets a test
            # feed fetch_cache's real completeness check a real cache.
            if self.seed_gomodcache is not None:
                self.seed_gomodcache(self.workdir / "gomodcache")
            return SimpleNamespace(stdout=self.go_list_stdout, returncode=0)
        raise AssertionError(f"unexpected subprocess call in fetch_cache: {argv}")


def run_fetch_cache(go_version_stdout, go_mod_text, go_list_stdout=None,
                     seed_gomodcache=None):
    """fetch_cache(), every subprocess call faked: returns (the SystemExit
    code fetch_cache raised, or None; its stderr; the FakeToolchain, to check
    whether `go list` ran)."""
    toolchain = FakeToolchain(go_version_stdout, go_mod_text, go_list_stdout,
                              seed_gomodcache)
    was_run = subprocess.run
    subprocess.run = toolchain
    stderr = io.StringIO()
    code = None
    try:
        with contextlib.redirect_stderr(stderr):
            try:
                go_mods.fetch_cache("https://example.invalid/repo.git", "f" * 40)
            except SystemExit as exc:
                code = exc.code
    finally:
        subprocess.run = was_run
        if toolchain.workdir is not None:
            shutil.rmtree(toolchain.workdir, ignore_errors=True)
    return code, stderr.getvalue(), toolchain


def refusal_path_cases():
    GO_VERSION = "go version go1.26.0 linux/amd64\n"

    # Equal: the app's own pinned floor, exactly met. Must proceed, not
    # refuse -- `have < need` is strict, not `<=`.
    code, err, tc = run_fetch_cache(GO_VERSION, GO_MOD_1260)
    case("fetch_cache: host go equal to the required version is not refused",
         code, None)
    case("fetch_cache: equal version still runs `go list`",
         tc.go_list_called, True)

    # Newer patch: the must-not-fire half of the same comparison.
    code, err, tc = run_fetch_cache(
        "go version go1.26.1 linux/amd64\n", GO_MOD_1260)
    case("fetch_cache: a newer host patch is not refused", code, None)

    # Older minor: THE case. Must refuse before `go list` ever runs.
    code, err, tc = run_fetch_cache(
        "go version go1.25.9 linux/amd64\n", GO_MOD_1260)
    case("fetch_cache: an older host minor is refused", code, 2)
    case("fetch_cache: refusal names both versions",
         "1.25.9" in err and "1.26.0" in err, True)
    case("fetch_cache: a refusal never runs `go list`",
         tc.go_list_called, False)

    # The two-component `go` directive form: same comparison, fed from
    # `_required_go_version`'s other branch.
    code, err, tc = run_fetch_cache(GO_VERSION, GO_MOD_1260_SHORT)
    case("fetch_cache: a two-component go.mod directive is not refused",
         code, None)

    # A devel host toolchain, read as its embedded 1.24 series (see
    # version_tuple_cases): behind a 1.26.0 floor, so it refuses here -- this
    # documents the parser's literal behaviour, not a claim that devel builds
    # are specially supported.
    case("fetch_cache: a devel host string reading behind is refused",
         run_fetch_cache(
             "go version devel go1.24-e705a02574 Tue Sep 26 15:22:01 2023 "
             "+0000 linux/amd64\n", GO_MOD_1260)[0],
         2)


# --- GOCACHE isolation -------------------------------------------------------
#
# GOMODCACHE already gets a fresh scratch dir per run; GOCACHE did not, so
# `go list -deps` ran against the host's shared, possibly-warm build cache.
# With a build already cached there, `go list` can report a module's package
# without ever extracting that module's .zip into GOMODCACHE -- silently
# dropping it from the rendered .inc. GOCACHE needs the same fresh-per-run
# treatment GOMODCACHE already has.

def gocache_isolation_cases():
    host_gocache = "/nonexistent/host/shared/go-build"
    was_gocache = os.environ.get("GOCACHE")
    os.environ["GOCACHE"] = host_gocache
    try:
        code, err, tc = run_fetch_cache(
            "go version go1.26.0 linux/amd64\n", GO_MOD_1260)
    finally:
        if was_gocache is None:
            os.environ.pop("GOCACHE", None)
        else:
            os.environ["GOCACHE"] = was_gocache

    gocache = (tc.go_list_env or {}).get("GOCACHE")
    case("fetch_cache: GOCACHE differs from the inherited host GOCACHE",
         gocache != host_gocache and gocache is not None, True)
    # Under the run's OWN temp root, alongside GOMODCACHE -- not some other
    # fixed, reused path, or a second run could warm it just the same way.
    case("fetch_cache: GOCACHE lies under the run's own temp root",
         gocache is not None and tc.workdir is not None
         and Path(gocache).resolve().is_relative_to(tc.workdir.resolve()),
         True)


# --- _deps_modules: the package stream reduced to (path, version) pairs ----
#
# `go list -json=Dir,Module -deps` emits one JSON object per PACKAGE, not per
# module, pretty-printed and concatenated (not a JSON array) -- several
# packages can share a module, a standard-library package carries no Module
# field at all, and the module being built is its own dependency, marked
# Main. _deps_modules reduces that stream to one (path, version) per
# package-providing, non-main module, in first-seen order.

def deps_modules_cases():
    def obj(module=None):
        rec = {"Dir": "/x"}
        if module is not None:
            rec["Module"] = module
        return json.dumps(rec, indent=2)

    main_mod = {"Path": "example.com/mainmod", "Version": "", "Main": True}
    a = {"Path": "example.com/a", "Version": "v1.0.0"}
    b = {"Path": "example.com/b", "Version": "v2.0.0"}

    # Objects joined by newlines, as go list's own pretty-printed,
    # concatenated (not comma-separated) objects are -- exercising the
    # inter-object whitespace skip along with every other property below.
    stream = "\n".join([obj(main_mod), obj(None), obj(a), obj(a), obj(b)])
    modules = go_mods._deps_modules(stream)

    case("_deps_modules: the main module is excluded",
         all(path != "example.com/mainmod" for path, _ in modules), True)
    case("_deps_modules: a std-library package (no Module field) is skipped",
         len(modules), 2)
    case("_deps_modules: a module repeated across packages is deduplicated",
         modules.count(("example.com/a", "v1.0.0")), 1)
    case("_deps_modules: first-seen order is preserved",
         modules, [("example.com/a", "v1.0.0"), ("example.com/b", "v2.0.0")])


# --- check_complete: every package-providing module needs its .zip ---------
#
# `go list -deps` reporting a module as providing a package means its
# source, not just its go.mod, was needed to build -- a cache holding only
# that module's .mod is incomplete. A module that provides no package never
# appears in `modules` at all, so a mod-only cache entry for it stays legal
# and is never asked about.

def check_complete_cases():
    with tempfile.TemporaryDirectory() as tmp:
        # THE case: a package-providing module (named in `modules`) whose
        # cache entry has only a .mod. Must be reported missing.
        seed(tmp, "example.com/nozip", "v1.0.0", "mod",
             b"module example.com/nozip\n")
        missing = go_mods.check_complete(
            [("example.com/nozip", "v1.0.0")], Path(tmp))
        case("check_complete: a package-providing module with only a .mod "
             "is reported missing",
             missing, [("example.com/nozip", "v1.0.0")])

    with tempfile.TemporaryDirectory() as tmp:
        # The must-not-fire half: the same module, its .zip now present too.
        seed(tmp, "example.com/haszip", "v1.0.0", "mod",
             b"module example.com/haszip\n")
        seed(tmp, "example.com/haszip", "v1.0.0", "zip",
             b"a fixture zip payload")
        missing = go_mods.check_complete(
            [("example.com/haszip", "v1.0.0")], Path(tmp))
        case("check_complete: a package-providing module with its .zip "
             "present is complete", missing, [])

    with tempfile.TemporaryDirectory() as tmp:
        # A mod-only module: present in the cache with only a .mod, but
        # never named in `modules` -- it provides no package, so this is not
        # a completeness failure.
        seed(tmp, "example.com/modonly", "v0.1.0", "mod",
             b"module example.com/modonly\n")
        missing = go_mods.check_complete([], Path(tmp))
        case("check_complete: a mod-only module absent from `modules` is "
             "not reported", missing, [])

    with tempfile.TemporaryDirectory() as tmp:
        # `go list -json`'s Module.Path is unescaped ("example.com/Foo"), but
        # the cache directory name is Go's on-disk escaping
        # ("example.com/!foo"). check_complete must convert before looking
        # up, or every module with an uppercase path segment would read as
        # missing regardless of whether its .zip is actually there.
        seed(tmp, "example.com/!foo", "v1.0.0", "zip", b"a fixture zip payload")
        missing = go_mods.check_complete(
            [("example.com/Foo", "v1.0.0")], Path(tmp))
        case("check_complete: an uppercase module path is escaped before "
             "the lookup, so its .zip is found",
             missing, [])


# --- check_complete is wired into fetch_cache's own refusal -----------------
#
# check_complete being correct in isolation does not prove fetch_cache acts
# on it -- these drive the completeness check through fetch_cache itself,
# with a real `go list -deps` stream and a real (fixture) GOMODCACHE.

def completeness_wiring_cases():
    GO_VERSION = "go version go1.26.0 linux/amd64\n"
    codegen_path, codegen_version = FakeToolchain.DEFAULT_MODULE
    # Two packages: the codegen tool's own module (fetch_cache refuses
    # outright without it, unrelated to completeness) and a second module
    # this case actually exercises.
    deps_stream = "\n".join(json.dumps(o) for o in (
        {"Dir": "/x", "Module": {"Path": codegen_path,
                                 "Version": codegen_version}},
        {"Dir": "/y", "Module": {"Path": "example.com/needed",
                                 "Version": "v1.0.0"}}))

    # THE case: overriding seed_gomodcache to seed only the codegen module
    # isolates exactly one missing module -- "example.com/needed".
    def seed_codegen_only(gomodcache):
        seed(gomodcache, codegen_path, codegen_version, "zip",
             b"fixture zip payload")

    code, err, tc = run_fetch_cache(
        GO_VERSION, GO_MOD_1260, go_list_stdout=deps_stream,
        seed_gomodcache=seed_codegen_only)
    case("fetch_cache: a module missing its .zip is refused", code, 2)
    case("fetch_cache: the refusal names the missing module",
         "example.com/needed@v1.0.0" in err, True)
    case("fetch_cache: the refusal does not also name a module that has "
         "its .zip", f"{codegen_path}@{codegen_version}" in err, False)

    # The must-not-fire half: both modules' .zip reach the cache --
    # overriding seed_gomodcache replaces the default entirely, so the
    # codegen module needs seeding here too, not just the one under test.
    def seed_both(gomodcache):
        seed(gomodcache, codegen_path, codegen_version, "zip",
             b"fixture zip payload")
        seed(gomodcache, "example.com/needed", "v1.0.0", "zip",
             b"a fixture zip payload")

    code, err, tc = run_fetch_cache(
        GO_VERSION, GO_MOD_1260, go_list_stdout=deps_stream,
        seed_gomodcache=seed_both)
    case("fetch_cache: a module with its .zip present is not refused",
         code, None)


# --- fetch_cache refuses when go list never names its own target -----------
#
# check_complete([]) reports an empty closure as trivially complete, so an
# empty, truncated or garbled `go list -deps` capture would otherwise render
# an empty .inc and report success. The codegen tool's own module always
# appears in a real result -- its absence means the capture cannot be
# trusted, checked before completeness rather than after.

def codegen_tool_presence_cases():
    GO_VERSION = "go version go1.26.0 linux/amd64\n"

    # THE case: no output at all -- explicit override, or the toolchain's
    # own "trusted, complete" default would mask exactly this.
    code, err, tc = run_fetch_cache(
        GO_VERSION, GO_MOD_1260, go_list_stdout="")
    case("fetch_cache: empty go list output refuses rather than reporting "
         "an empty closure complete", code, 2)
    case("fetch_cache: the refusal names the codegen tool's import path",
         go_mods.CODEGEN_TOOL in err, True)

    # Non-empty, but the codegen tool's own module never appears -- the
    # same refusal, not merely an empty-stream special case. Its own .zip
    # IS seeded, so completeness alone would not also refuse: only this
    # check can be responsible for what happens here.
    unrelated = json.dumps({"Dir": "/x",
                            "Module": {"Path": "gopkg.in/yaml.v3",
                                      "Version": "v3.0.1"}})

    def seed_unrelated(gomodcache):
        seed(gomodcache, "gopkg.in/yaml.v3", "v3.0.1", "zip",
             b"fixture zip payload")

    code, err, tc = run_fetch_cache(
        GO_VERSION, GO_MOD_1260, go_list_stdout=unrelated,
        seed_gomodcache=seed_unrelated)
    case("fetch_cache: a deps list missing the codegen tool's module "
         "refuses even when otherwise complete", code, 2)
    case("fetch_cache: that refusal names the codegen tool, not a "
         "completeness complaint", go_mods.CODEGEN_TOOL in err, True)

    # A module path that is a raw STRING prefix of CODEGEN_TOOL but not a
    # package-path-boundary ancestor of it -- CODEGEN_TOOL continues
    # "-codegen/v2/..." right after this path, not "/...". Its own .zip is
    # seeded, so only a boundary check (not a bare startswith) can tell this
    # apart from the codegen tool's real module.
    near_miss_path = "github.com/oapi-codegen/oapi"
    near_miss_version = "v1.0.0"
    near_miss = json.dumps({"Dir": "/x",
                            "Module": {"Path": near_miss_path,
                                      "Version": near_miss_version}})

    def seed_near_miss(gomodcache):
        seed(gomodcache, near_miss_path, near_miss_version, "zip",
             b"fixture zip payload")

    code, err, tc = run_fetch_cache(
        GO_VERSION, GO_MOD_1260, go_list_stdout=near_miss,
        seed_gomodcache=seed_near_miss)
    case("fetch_cache: a string-prefix, non-boundary module is not "
         "mistaken for the codegen tool's own module", code, 2)
    case("fetch_cache: that refusal names the codegen tool",
         go_mods.CODEGEN_TOOL in err, True)


# --- current_srcrev: the "already current" seam for skip-when-current -----

def current_srcrev_cases():
    with tempfile.TemporaryDirectory() as tmp:
        inc_path = Path(tmp) / "wisekiosk-backend-go-mods.inc"
        inc_path.write_text(
            f'WISEKIOSK_GOMODS_SRCREV = "{SRCREV}"\n')
        case("current_srcrev: reads the srcrev an existing .inc records",
             go_mods.current_srcrev(inc_path), SRCREV)

    with tempfile.TemporaryDirectory() as tmp:
        inc_path = Path(tmp) / "wisekiosk-backend-go-mods.inc"
        inc_path.write_text('SRC_URI += "https://example.invalid/x.zip"\n')
        case("current_srcrev: an .inc carrying no such variable is None",
             go_mods.current_srcrev(inc_path), None)

    case("current_srcrev: a path that does not exist is None",
         go_mods.current_srcrev(Path("/nonexistent/wisekiosk-backend-go-mods.inc")),
         None)


def main() -> int:
    header_cases()
    entry_shape_cases()
    mod_only_cases()
    escaping_and_sort_cases()
    version_tuple_cases()
    required_go_version_cases()
    refusal_path_cases()
    gocache_isolation_cases()
    deps_modules_cases()
    check_complete_cases()
    completeness_wiring_cases()
    codegen_tool_presence_cases()
    current_srcrev_cases()
    print(f"\npass={len(PASS)} fail={len(FAIL)} skip=0")
    return 1 if FAIL else 0


if __name__ == "__main__":
    sys.exit(main())
