#!/usr/bin/env python3
"""Self-test for tools/go-mods.py's rendering seam. Run by `just guards` and by CI.

    go-mods-test.py             -- every case

`render_inc(cache_dir, srcrev)` is the importable seam: it walks a GOMODCACHE
laid out exactly as `go mod download` leaves one (`cache/download/<escaped
module path>/@v/<version>.{zip,mod,...}`) and renders the recipe include. Every
fixture here IS such a cache, fabricated small enough to read -- never a real
`go list`/clone, which needs network the guard must not depend on.

The escaped path segments below reuse Go's own on-disk escaping (an uppercase
letter becomes `!` + its lower-case form): the walk reads directory names
as-is off disk, so a fixture with a literal `!x` segment is what an uppercase
module path actually looks like in GOMODCACHE, not a re-implementation of the
escaping rule.
"""
import hashlib
import importlib.util
import sys
import tempfile
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
sys.dont_write_bytecode = True


def load(name):
    spec = importlib.util.spec_from_file_location(
        name.replace("-", "_"), TOOLS / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


go_mods = load("go-mods")

PASS, FAIL = [], []


def case(name, got, want):
    (PASS if got == want else FAIL).append(name)
    if got != want:
        print(f"FAIL  {name}\n        want {want!r}\n        got  {got!r}")


SRCREV = "1becdf0dd12943bc7f98d6d52a76494bef02fb1f"


def seed(gomodcache, escaped, version, ext, content):
    """One file at the exact path `go mod download` would leave it."""
    p = Path(gomodcache) / "cache" / "download" / escaped / "@v" / f"{version}.{ext}"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_bytes(content)
    return p


def entry_id(escaped, version, ext):
    digest = hashlib.sha256(f"{escaped}@{version}.{ext}".encode()).hexdigest()
    return f"gomod_{digest[:16]}"


def entry_lines(escaped, version, ext, sha256hex):
    """The exact two-line SRC_URI pair the plan specifies for one file."""
    ident = entry_id(escaped, version, ext)
    url = f"https://proxy.golang.org/{escaped}/@v/{version}.{ext}"
    downloadfilename = f"gomod/{escaped}/@v/{version}.{ext}"
    subdir = f"goproxy/{escaped}/@v"
    return [
        f'SRC_URI += "{url};downloadfilename={downloadfilename};'
        f'subdir={subdir};unpack=0;name={ident}"',
        f'SRC_URI[{ident}.sha256sum] = "{sha256hex}"',
    ]


def src_uri_lines(rendered):
    """Only the SRC_URI body lines, in order -- independent of whatever
    blank-line or comment layout the generator puts around them, which the
    plan does not specify."""
    return [ln for ln in rendered.splitlines() if ln.startswith("SRC_URI")]


def header_cases():
    with tempfile.TemporaryDirectory() as tmp:
        seed(tmp, "example.com/a", "v1.0.0", "zip", b"zip-bytes")
        seed(tmp, "example.com/a", "v1.0.0", "mod", b"mod-bytes")
        rendered = go_mods.render_inc(Path(tmp), SRCREV)
    case("render_inc: first line is the exact generated-by header",
         rendered.splitlines()[0],
         f"# Generated by tools/go-mods.py from WiseKiosk {SRCREV}; do not edit.")


def entry_shape_cases():
    """One module, one version, both files: the exact SRC_URI entry form,
    the id derivation, and that sha256 is taken over the real fixture bytes."""
    zip_bytes = b"a fixture zip payload, not a real Go module"
    mod_bytes = b"module example.com/a\n\ngo 1.24\n"
    with tempfile.TemporaryDirectory() as tmp:
        seed(tmp, "example.com/a", "v1.0.0", "zip", zip_bytes)
        seed(tmp, "example.com/a", "v1.0.0", "mod", mod_bytes)
        lines = src_uri_lines(go_mods.render_inc(Path(tmp), SRCREV))

    want = (
        entry_lines("example.com/a", "v1.0.0", "zip",
                    hashlib.sha256(zip_bytes).hexdigest())
        + entry_lines("example.com/a", "v1.0.0", "mod",
                      hashlib.sha256(mod_bytes).hexdigest())
    )
    case("render_inc: zip-then-mod, exact SRC_URI entry form and sha256",
         lines, want)


def mod_only_cases():
    """A version with a .mod but no .zip (a module used only for its go.mod,
    e.g. a transitive dependency of the build list) emits the .mod alone."""
    mod_bytes = b"module example.com/modonly\n\ngo 1.24\n"
    with tempfile.TemporaryDirectory() as tmp:
        seed(tmp, "example.com/modonly", "v0.1.0", "mod", mod_bytes)
        lines = src_uri_lines(go_mods.render_inc(Path(tmp), SRCREV))

    case("render_inc: a mod-only version emits exactly one SRC_URI pair",
         len(lines), 2)
    case("render_inc: a mod-only version emits only the .mod entry",
         lines,
         entry_lines("example.com/modonly", "v0.1.0", "mod",
                     hashlib.sha256(mod_bytes).hexdigest()))


def escaping_and_sort_cases():
    """Four modules seeded out of order, one with an uppercase-escaped
    segment and one with two versions -- render_inc must sort by escaped
    path then version, and preserve the escaped segment verbatim (it is
    already how Go's own cache spells an uppercase path, not something
    render_inc re-derives)."""
    files = {
        ("example.com/b", "v1.0.0", "zip"): b"b-zip",
        ("example.com/b", "v1.0.0", "mod"): b"b-mod",
        ("example.com/!x", "v1.0.0", "zip"): b"bangx-zip",
        ("example.com/!x", "v1.0.0", "mod"): b"bangx-mod",
        ("example.com/a", "v2.0.0", "mod"): b"a-v2-mod",
        ("example.com/a", "v1.0.0", "zip"): b"a-v1-zip",
        ("example.com/a", "v1.0.0", "mod"): b"a-v1-mod",
    }
    # Seeded in an order that is neither sorted-by-path nor sorted-by-version,
    # so a generator that merely preserves filesystem walk order would not
    # accidentally pass this.
    order = [
        ("example.com/b", "v1.0.0", "zip"),
        ("example.com/a", "v2.0.0", "mod"),
        ("example.com/!x", "v1.0.0", "mod"),
        ("example.com/a", "v1.0.0", "zip"),
        ("example.com/!x", "v1.0.0", "zip"),
        ("example.com/a", "v1.0.0", "mod"),
        ("example.com/b", "v1.0.0", "mod"),
    ]
    with tempfile.TemporaryDirectory() as tmp:
        for key in order:
            escaped, version, ext = key
            seed(tmp, escaped, version, ext, files[key])
        lines = src_uri_lines(go_mods.render_inc(Path(tmp), SRCREV))

    want = []
    for escaped, version, ext in (
        ("example.com/!x", "v1.0.0", "zip"),
        ("example.com/!x", "v1.0.0", "mod"),
        ("example.com/a", "v1.0.0", "zip"),
        ("example.com/a", "v1.0.0", "mod"),
        ("example.com/a", "v2.0.0", "mod"),
        ("example.com/b", "v1.0.0", "zip"),
        ("example.com/b", "v1.0.0", "mod"),
    ):
        want += entry_lines(escaped, version, ext,
                             hashlib.sha256(files[(escaped, version, ext)])
                             .hexdigest())

    case("render_inc: sorted by case-escaped path then version, "
         "zip before mod, uppercase escaping preserved verbatim",
         lines, want)


def check_cases():
    """`--check` without network. Team-lead ruling: go-mods.py exposes
    `fetch_cache(url, srcrev) -> Path` (the only network-touching function)
    and a module constant `INC_PATH` (the committed .inc path); `check(url,
    srcrev)` is `render_inc(fetch_cache(url, srcrev), srcrev)` compared
    against INC_PATH's content, exit 1 on drift / 0 on match. Tests
    monkeypatch both seams -- the same pattern cve-tools-test.py uses for
    layer-currency.py's check() via `currency.repo_top`/`currency.ls_remote`."""
    url = "https://example.invalid/WiseKiosk.git"
    srcrev = "f" * 40
    zip_bytes = b"a fixture zip payload for --check"
    mod_bytes = b"module example.com/checkfixture\n\ngo 1.24\n"

    with tempfile.TemporaryDirectory() as tmp:
        cache_dir = Path(tmp) / "gomodcache"
        seed(cache_dir, "example.com/checkfixture", "v1.0.0", "zip", zip_bytes)
        seed(cache_dir, "example.com/checkfixture", "v1.0.0", "mod", mod_bytes)
        current = go_mods.render_inc(cache_dir, srcrev)
        inc_path = Path(tmp) / "committed.inc"

        was_fetch, was_inc = go_mods.fetch_cache, go_mods.INC_PATH
        go_mods.fetch_cache = lambda u, s: cache_dir
        try:
            inc_path.write_text(current)
            go_mods.INC_PATH = inc_path
            case("check: exits 0 when the committed .inc matches the "
                 "regenerated one",
                 go_mods.check(url, srcrev), 0)

            # Seeded drift: the committed .inc is stale (as if SRCREV moved
            # and nobody re-ran the generator) -- the bytes on disk no longer
            # match what render_inc produces for the fixture cache.
            inc_path.write_text(current.replace(srcrev, "0" * 40))
            case("check: exits 1 on a seeded drift (stale committed .inc)",
                 go_mods.check(url, srcrev), 1)
        finally:
            go_mods.fetch_cache, go_mods.INC_PATH = was_fetch, was_inc


def main() -> int:
    header_cases()
    entry_shape_cases()
    mod_only_cases()
    escaping_and_sort_cases()
    check_cases()
    print(f"\npass={len(PASS)} fail={len(FAIL)} skip=0")
    return 1 if FAIL else 0


if __name__ == "__main__":
    sys.exit(main())
