"""The device-side unit-wellformedness tier's own judgement (#206, step 4 of #202; the owner's
lens correction moved `systemd-analyze verify` to the board, and the ruling after the e5b3fd0 job
replaced a returncode/`--generators=yes` approach with this one: `data.mount` is not a unit file in
the image, it is produced at boot by systemd's fstab generator (confirmed on bench: `systemctl cat
data.mount` shows `# Automatically generated by systemd-fstab-generator`), and plain `verify` never
sees it -- `--generators=yes` tried and measured no different. A "Unit X not found" line is not
itself a defect when the board's own `systemctl is-active X` says X is running; case.py asks that
question for every name verify reports missing and hands the answer map here.

Pure: verify's own output text and a {name: is-active answer} map in, an (outcome, reason) tuple
out -- no self.target, no subprocess, no network. case.py collects every input through
self.target.run; this module only judges what came back.
"""
import re

NOT_FOUND = re.compile(r"Unit (\S+) not found")


def verdict(verify_output, active_units):
    """verify_output is case.py's own scoped text for one unit (every line
    naming unit names other than the one under test already stripped).
    Every line matching NOT_FOUND is dropped when active_units maps that
    name to "active" -- generator-provided, not a defect; every other
    line, and a not-found line whose name is not active (or not in
    active_units at all), survives. "ok" iff nothing survives; "error"
    naming every surviving line verbatim."""
    remaining = []
    for line in verify_output.splitlines():
        if not line.strip():
            continue
        match = NOT_FOUND.search(line)
        if match and active_units.get(match.group(1)) == "active":
            continue
        remaining.append(line)
    if remaining:
        return "error", "; ".join(remaining)
    return "ok", "systemd-analyze verify reported no problems once generator-provided mounts are accounted for"
