HTTP/1.1 200 OK
Date: Fri, 09 Oct 2026 13:02:24 GMT
Content-Type: application/json; charset=utf-8
access-control-allow-origin: *
access-control-expose-headers: RateLimit-Limit,RateLimit-Policy,RateLimit-Remaining,RateLimit-Reset,RateLimit-History-Limit,RateLimit-History-Policy,RateLimit-History-Remaining,RateLimit-History-Reset,Retry-After
Cache-Control: public, max-age=60, s-maxage=60
content-security-policy: default-src 'self';style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://unpkg.com;script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://unpkg.com;font-src 'self' https://cdn.jsdelivr.net;connect-src 'self' https://unpkg.com https://cdn.jsdelivr.net;img-src 'self' data: https:;base-uri 'self';form-action 'self';frame-ancestors 'self';object-src 'none';script-src-attr 'none';upgrade-insecure-requests
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-origin
etag: W/"c666-JZPWMScS4VVh+FKXfyjvOryccEE"
nel: {"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}
origin-agent-cluster: ?1
ratelimit-limit: 300
ratelimit-policy: 300;w=60
ratelimit-remaining: 218
ratelimit-reset: 34
referrer-policy: no-referrer
report-to: {"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=h6%2FBmDdWhnTy1Xo2ttM7wpXglE9FZ71mu70rfBniUog%3D\u0026sid=c4c9725f-1ab0-44d8-820f-430df2718e11\u0026ts=1791550893"}],"max_age":3600}
reporting-endpoints: heroku-nel="https://nel.heroku.com/reports?s=h6%2FBmDdWhnTy1Xo2ttM7wpXglE9FZ71mu70rfBniUog%3D&sid=c4c9725f-1ab0-44d8-820f-430df2718e11&ts=1791550893"
Server: cloudflare
strict-transport-security: max-age=2592000
vary: Accept-Encoding
via: 2.0 heroku-router
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-request-id: ada79598-033c-fe85-5288-f681b0dbc9af
x-xss-protection: 0
Age: 51
cf-cache-status: HIT
CF-RAY: a47d945ced1d2af6-MIA
alt-svc: h3=":443"; ma=86400
Content-Length: 50790

{
  "id": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
  "name": "Disney's Hollywood Studios",
  "entityType": "PARK",
  "timezone": "America/New_York",
  "liveData": [
    {
      "id": "02861a9b-584d-47d5-a8d0-98e05c3b5dce",
      "name": "Meet Disney Stars at Red Carpet Dreams",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "18368386;entityType=Entertainment",
      "queue": {
        "STANDBY": {
          "waitTime": null
        }
      },
      "status": "CLOSED",
      "showtimes": [
        {
          "type": "Operating",
          "endTime": "2026-10-08T20:00:00-04:00",
          "startTime": "2026-10-08T09:00:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T00:01:09.149Z"
    },
    {
      "id": "0e7426d1-7406-4e7c-9da6-ac6c126211c6",
      "name": "Meet Joy at Pixar Plaza",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "411908664;entityType=Entertainment",
      "status": "OPERATING",
      "showtimes": [
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T09:30:00-04:00",
          "startTime": "2026-10-09T09:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T10:00:00-04:00",
          "startTime": "2026-10-09T10:00:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T10:30:00-04:00",
          "startTime": "2026-10-09T10:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T11:00:00-04:00",
          "startTime": "2026-10-09T11:00:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T11:30:00-04:00",
          "startTime": "2026-10-09T11:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T12:00:00-04:00",
          "startTime": "2026-10-09T12:00:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T12:30:00-04:00",
          "startTime": "2026-10-09T12:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T14:00:00-04:00",
          "startTime": "2026-10-09T14:00:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T14:30:00-04:00",
          "startTime": "2026-10-09T14:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T15:00:00-04:00",
          "startTime": "2026-10-09T15:00:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T15:30:00-04:00",
          "startTime": "2026-10-09T15:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T16:00:00-04:00",
          "startTime": "2026-10-09T16:00:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T12:02:08.002Z"
    },
    {
      "id": "1a2e70d9-50d5-4140-b69e-799e950f7d18",
      "name": "Star Wars: Rise of the Resistance",
      "entityType": "ATTRACTION",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "19263736;entityType=Attraction",
      "queue": {
        "STANDBY": {
          "waitTime": 60
        },
        "SINGLE_RIDER": {
          "waitTime": null
        },
        "PAID_RETURN_TIME": {
          "price": {
            "amount": 2500,
            "currency": "USD",
            "formatted": "$25.00"
          },
          "state": "FINISHED",
          "returnEnd": null,
          "returnStart": null
        }
      },
      "status": "OPERATING",
      "forecast": [
        {
          "time": "2026-10-09T08:00:00-04:00",
          "waitTime": 35,
          "percentage": 26
        },
        {
          "time": "2026-10-09T09:00:00-04:00",
          "waitTime": 60,
          "percentage": 45
        },
        {
          "time": "2026-10-09T10:00:00-04:00",
          "waitTime": 65,
          "percentage": 49
        },
        {
          "time": "2026-10-09T11:00:00-04:00",
          "waitTime": 70,
          "percentage": 53
        },
        {
          "time": "2026-10-09T12:00:00-04:00",
          "waitTime": 70,
          "percentage": 53
        },
        {
          "time": "2026-10-09T13:00:00-04:00",
          "waitTime": 65,
          "percentage": 49
        },
        {
          "time": "2026-10-09T14:00:00-04:00",
          "waitTime": 70,
          "percentage": 53
        },
        {
          "time": "2026-10-09T15:00:00-04:00",
          "waitTime": 70,
          "percentage": 53
        },
        {
          "time": "2026-10-09T16:00:00-04:00",
          "waitTime": 45,
          "percentage": 34
        },
        {
          "time": "2026-10-09T17:00:00-04:00",
          "waitTime": 45,
          "percentage": 34
        },
        {
          "time": "2026-10-09T18:00:00-04:00",
          "waitTime": 70,
          "percentage": 53
        },
        {
          "time": "2026-10-09T19:00:00-04:00",
          "waitTime": 45,
          "percentage": 34
        },
        {
          "time": "2026-10-09T20:00:00-04:00",
          "waitTime": 35,
          "percentage": 26
        }
      ],
      "operatingHours": [
        {
          "type": "Early Entry",
          "endTime": "2026-10-09T08:30:00-04:00",
          "startTime": "2026-10-09T08:00:00-04:00"
        },
        {
          "type": "Operating",
          "endTime": "2026-10-09T21:00:00-04:00",
          "startTime": "2026-10-09T08:30:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T12:29:12.121Z"
    },
    {
      "id": "1bbce25c-36eb-4d16-9216-4a1bbd46932b",
      "name": "Disney Jr. Mickey Mouse Clubhouse Live!",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "412521565;entityType=Entertainment",
      "queue": {
        "RETURN_TIME": {
          "state": "AVAILABLE",
          "returnEnd": "2026-10-09T12:55:00-04:00",
          "returnStart": "2026-10-09T11:55:00-04:00"
        }
      },
      "status": "OPERATING",
      "showtimes": [
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T10:15:00-04:00",
          "startTime": "2026-10-09T10:15:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T11:15:00-04:00",
          "startTime": "2026-10-09T11:15:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T12:15:00-04:00",
          "startTime": "2026-10-09T12:15:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T13:15:00-04:00",
          "startTime": "2026-10-09T13:15:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T15:05:00-04:00",
          "startTime": "2026-10-09T15:05:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T15:55:00-04:00",
          "startTime": "2026-10-09T15:55:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T16:45:00-04:00",
          "startTime": "2026-10-09T16:45:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T17:35:00-04:00",
          "startTime": "2026-10-09T17:35:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T04:04:21.404Z"
    },
    {
      "id": "20b5daa8-e1ea-436f-830c-2d7d18d929b5",
      "name": "Toy Story Mania!",
      "entityType": "ATTRACTION",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "209857;entityType=Attraction",
      "queue": {
        "STANDBY": {
          "waitTime": 15
        },
        "RETURN_TIME": {
          "state": "FINISHED",
          "returnEnd": null,
          "returnStart": null
        }
      },
      "status": "OPERATING",
      "forecast": [
        {
          "time": "2026-10-09T08:00:00-04:00",
          "waitTime": 15,
          "percentage": 12
        },
        {
          "time": "2026-10-09T09:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T10:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T11:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T12:00:00-04:00",
          "waitTime": 50,
          "percentage": 41
        },
        {
          "time": "2026-10-09T13:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T14:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T15:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T16:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T17:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T18:00:00-04:00",
          "waitTime": 50,
          "percentage": 41
        },
        {
          "time": "2026-10-09T19:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T20:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        }
      ],
      "operatingHours": [
        {
          "type": "Early Entry",
          "endTime": "2026-10-09T08:30:00-04:00",
          "startTime": "2026-10-09T08:00:00-04:00"
        },
        {
          "type": "Operating",
          "endTime": "2026-10-09T21:00:00-04:00",
          "startTime": "2026-10-09T08:30:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T13:01:10.708Z"
    },
    {
      "id": "27f9fc86-2341-4bf4-8cbf-67fc16a841f1",
      "name": "Meet Olaf at Celebrity Spotlight",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "18368385;entityType=Entertainment",
      "queue": {
        "STANDBY": {
          "waitTime": null
        }
      },
      "status": "CLOSED",
      "showtimes": [
        {
          "type": "Operating",
          "endTime": "2026-10-08T18:00:00-04:00",
          "startTime": "2026-10-08T09:00:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-08T22:01:04.651Z"
    },
    {
      "id": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "name": "Disney's Hollywood Studios",
      "entityType": "PARK",
      "parkId": null,
      "externalId": "80007998;entityType=theme-park",
      "queue": {
        "STANDBY": {
          "waitTime": null
        }
      },
      "status": "OPERATING",
      "lastUpdated": "2024-05-14T13:36:04.210Z"
    },
    {
      "id": "30070790-e166-4135-b7ce-d89da20a7b95",
      "name": "Meet Disney Jr. Stars on Commissary Lane",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "412636198;entityType=Entertainment",
      "status": "CLOSED",
      "showtimes": [],
      "lastUpdated": "2026-09-13T09:55:26.056Z"
    },
    {
      "id": "343de9f4-e100-4a52-9285-0fcc3a486603",
      "name": "First Order Searches for the Resistance",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "411979428;entityType=Entertainment",
      "status": "OPERATING",
      "showtimes": [
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T12:30:00-04:00",
          "startTime": "2026-10-09T12:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T13:30:00-04:00",
          "startTime": "2026-10-09T13:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T14:30:00-04:00",
          "startTime": "2026-10-09T14:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T16:30:00-04:00",
          "startTime": "2026-10-09T16:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T17:30:00-04:00",
          "startTime": "2026-10-09T17:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T18:30:00-04:00",
          "startTime": "2026-10-09T18:30:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T04:04:21.339Z"
    },
    {
      "id": "34c4916b-989b-4ff1-a7e3-a6a846a3484f",
      "name": "Millennium Falcon: Smugglers Run",
      "entityType": "ATTRACTION",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "19263735;entityType=Attraction",
      "queue": {
        "STANDBY": {
          "waitTime": 15
        },
        "RETURN_TIME": {
          "state": "AVAILABLE",
          "returnEnd": "2026-10-09T11:30:00-04:00",
          "returnStart": "2026-10-09T10:30:00-04:00"
        },
        "SINGLE_RIDER": {
          "waitTime": null
        }
      },
      "status": "OPERATING",
      "forecast": [
        {
          "time": "2026-10-09T08:00:00-04:00",
          "waitTime": 15,
          "percentage": 12
        },
        {
          "time": "2026-10-09T09:00:00-04:00",
          "waitTime": 20,
          "percentage": 16
        },
        {
          "time": "2026-10-09T10:00:00-04:00",
          "waitTime": 40,
          "percentage": 33
        },
        {
          "time": "2026-10-09T11:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T12:00:00-04:00",
          "waitTime": 40,
          "percentage": 33
        },
        {
          "time": "2026-10-09T13:00:00-04:00",
          "waitTime": 50,
          "percentage": 41
        },
        {
          "time": "2026-10-09T14:00:00-04:00",
          "waitTime": 40,
          "percentage": 33
        },
        {
          "time": "2026-10-09T15:00:00-04:00",
          "waitTime": 25,
          "percentage": 20
        },
        {
          "time": "2026-10-09T16:00:00-04:00",
          "waitTime": 20,
          "percentage": 16
        },
        {
          "time": "2026-10-09T17:00:00-04:00",
          "waitTime": 20,
          "percentage": 16
        },
        {
          "time": "2026-10-09T18:00:00-04:00",
          "waitTime": 20,
          "percentage": 16
        },
        {
          "time": "2026-10-09T19:00:00-04:00",
          "waitTime": 20,
          "percentage": 16
        },
        {
          "time": "2026-10-09T20:00:00-04:00",
          "waitTime": 15,
          "percentage": 12
        }
      ],
      "operatingHours": [
        {
          "type": "Early Entry",
          "endTime": "2026-10-09T08:30:00-04:00",
          "startTime": "2026-10-09T08:00:00-04:00"
        },
        {
          "type": "Operating",
          "endTime": "2026-10-09T21:00:00-04:00",
          "startTime": "2026-10-09T08:30:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T12:59:26.255Z"
    },
    {
      "id": "375197ac-27ac-41f7-bd93-f4e9b9fc4d5d",
      "name": "Beauty and the Beast – Live on Stage",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "80010848;entityType=Entertainment",
      "queue": {
        "RETURN_TIME": {
          "state": "AVAILABLE",
          "returnEnd": "2026-10-09T11:30:00-04:00",
          "returnStart": "2026-10-09T10:30:00-04:00"
        }
      },
      "status": "OPERATING",
      "showtimes": [
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T11:00:00-04:00",
          "startTime": "2026-10-09T11:00:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T13:00:00-04:00",
          "startTime": "2026-10-09T13:00:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T14:00:00-04:00",
          "startTime": "2026-10-09T14:00:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T16:00:00-04:00",
          "startTime": "2026-10-09T16:00:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T17:00:00-04:00",
          "startTime": "2026-10-09T17:00:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T04:04:21.448Z"
    },
    {
      "id": "399aa0a1-98e2-4d2b-b297-2b451e9665e1",
      "name": "Slinky Dog Dash",
      "entityType": "ATTRACTION",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "18904138;entityType=Attraction",
      "queue": {
        "STANDBY": {
          "waitTime": null
        },
        "RETURN_TIME": {
          "state": "FINISHED",
          "returnEnd": null,
          "returnStart": null
        }
      },
      "status": "DOWN",
      "operatingHours": [
        {
          "type": "Early Entry",
          "endTime": "2026-10-09T08:30:00-04:00",
          "startTime": "2026-10-09T08:00:00-04:00"
        },
        {
          "type": "Operating",
          "endTime": "2026-10-09T21:00:00-04:00",
          "startTime": "2026-10-09T08:30:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T12:03:13.306Z"
    },
    {
      "id": "3b290419-8ca2-44bc-a710-a6c83fca76ec",
      "name": "Star Tours – The Adventures Continue",
      "entityType": "ATTRACTION",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "80010193;entityType=Attraction",
      "queue": {
        "STANDBY": {
          "waitTime": 5
        },
        "RETURN_TIME": {
          "state": "AVAILABLE",
          "returnEnd": "2026-10-09T12:10:00-04:00",
          "returnStart": "2026-10-09T11:10:00-04:00"
        }
      },
      "status": "OPERATING",
      "forecast": [
        {
          "time": "2026-10-09T08:00:00-04:00",
          "waitTime": 5,
          "percentage": 4
        },
        {
          "time": "2026-10-09T09:00:00-04:00",
          "waitTime": 5,
          "percentage": 4
        },
        {
          "time": "2026-10-09T10:00:00-04:00",
          "waitTime": 15,
          "percentage": 12
        },
        {
          "time": "2026-10-09T11:00:00-04:00",
          "waitTime": 20,
          "percentage": 16
        },
        {
          "time": "2026-10-09T12:00:00-04:00",
          "waitTime": 15,
          "percentage": 12
        },
        {
          "time": "2026-10-09T13:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T14:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T15:00:00-04:00",
          "waitTime": 5,
          "percentage": 4
        },
        {
          "time": "2026-10-09T16:00:00-04:00",
          "waitTime": 5,
          "percentage": 4
        },
        {
          "time": "2026-10-09T17:00:00-04:00",
          "waitTime": 5,
          "percentage": 4
        },
        {
          "time": "2026-10-09T18:00:00-04:00",
          "waitTime": 5,
          "percentage": 4
        },
        {
          "time": "2026-10-09T19:00:00-04:00",
          "waitTime": 5,
          "percentage": 4
        },
        {
          "time": "2026-10-09T20:00:00-04:00",
          "waitTime": 5,
          "percentage": 4
        }
      ],
      "operatingHours": [
        {
          "type": "Early Entry",
          "endTime": "2026-10-09T08:30:00-04:00",
          "startTime": "2026-10-09T08:00:00-04:00"
        },
        {
          "type": "Operating",
          "endTime": "2026-10-09T21:00:00-04:00",
          "startTime": "2026-10-09T08:30:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T12:59:26.360Z"
    },
    {
      "id": "42328c39-76ab-4f03-b862-4206c8d9f7bb",
      "name": "Fantasmic!",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "80010887;entityType=Entertainment",
      "status": "OPERATING",
      "showtimes": [
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T20:00:00-04:00",
          "startTime": "2026-10-09T20:00:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T21:30:00-04:00",
          "startTime": "2026-10-09T21:30:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T04:04:21.477Z"
    },
    {
      "id": "69cb35f2-c58e-4b44-88c9-ea0cc720e075",
      "name": "Disney Villains: Unfairly Ever After",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "412328859;entityType=Entertainment",
      "status": "OPERATING",
      "showtimes": [
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T10:30:00-04:00",
          "startTime": "2026-10-09T10:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T11:10:00-04:00",
          "startTime": "2026-10-09T11:10:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T11:50:00-04:00",
          "startTime": "2026-10-09T11:50:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T12:30:00-04:00",
          "startTime": "2026-10-09T12:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T13:10:00-04:00",
          "startTime": "2026-10-09T13:10:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T13:50:00-04:00",
          "startTime": "2026-10-09T13:50:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T14:30:00-04:00",
          "startTime": "2026-10-09T14:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T15:10:00-04:00",
          "startTime": "2026-10-09T15:10:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T15:50:00-04:00",
          "startTime": "2026-10-09T15:50:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T16:30:00-04:00",
          "startTime": "2026-10-09T16:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T17:10:00-04:00",
          "startTime": "2026-10-09T17:10:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T17:50:00-04:00",
          "startTime": "2026-10-09T17:50:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T18:30:00-04:00",
          "startTime": "2026-10-09T18:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T19:10:00-04:00",
          "startTime": "2026-10-09T19:10:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T19:50:00-04:00",
          "startTime": "2026-10-09T19:50:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T04:04:21.389Z"
    },
    {
      "id": "6e118e37-5002-408d-9d88-0b5d9cdb5d14",
      "name": "Mickey & Minnie's Runaway Railway",
      "entityType": "ATTRACTION",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "19259335;entityType=Attraction",
      "queue": {
        "STANDBY": {
          "waitTime": 45
        },
        "RETURN_TIME": {
          "state": "AVAILABLE",
          "returnEnd": "2026-10-09T13:00:00-04:00",
          "returnStart": "2026-10-09T12:00:00-04:00"
        }
      },
      "status": "OPERATING",
      "forecast": [
        {
          "time": "2026-10-09T08:00:00-04:00",
          "waitTime": 20,
          "percentage": 16
        },
        {
          "time": "2026-10-09T09:00:00-04:00",
          "waitTime": 35,
          "percentage": 29
        },
        {
          "time": "2026-10-09T10:00:00-04:00",
          "waitTime": 50,
          "percentage": 41
        },
        {
          "time": "2026-10-09T11:00:00-04:00",
          "waitTime": 55,
          "percentage": 45
        },
        {
          "time": "2026-10-09T12:00:00-04:00",
          "waitTime": 55,
          "percentage": 45
        },
        {
          "time": "2026-10-09T13:00:00-04:00",
          "waitTime": 50,
          "percentage": 41
        },
        {
          "time": "2026-10-09T14:00:00-04:00",
          "waitTime": 50,
          "percentage": 41
        },
        {
          "time": "2026-10-09T15:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T16:00:00-04:00",
          "waitTime": 40,
          "percentage": 33
        },
        {
          "time": "2026-10-09T17:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T18:00:00-04:00",
          "waitTime": 40,
          "percentage": 33
        },
        {
          "time": "2026-10-09T19:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T20:00:00-04:00",
          "waitTime": 35,
          "percentage": 29
        }
      ],
      "operatingHours": [
        {
          "type": "Early Entry",
          "endTime": "2026-10-09T08:30:00-04:00",
          "startTime": "2026-10-09T08:00:00-04:00"
        },
        {
          "type": "Operating",
          "endTime": "2026-10-09T21:00:00-04:00",
          "startTime": "2026-10-09T08:30:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T12:59:26.246Z"
    },
    {
      "id": "6f6998e8-a629-412c-b964-2cb06af8e26b",
      "name": "The Twilight Zone™ Tower of Terror",
      "entityType": "ATTRACTION",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "80010218;entityType=Attraction",
      "queue": {
        "STANDBY": {
          "waitTime": 13
        },
        "RETURN_TIME": {
          "state": "AVAILABLE",
          "returnEnd": "2026-10-09T18:25:00-04:00",
          "returnStart": "2026-10-09T17:25:00-04:00"
        }
      },
      "status": "OPERATING",
      "forecast": [
        {
          "time": "2026-10-09T08:00:00-04:00",
          "waitTime": 15,
          "percentage": 12
        },
        {
          "time": "2026-10-09T09:00:00-04:00",
          "waitTime": 20,
          "percentage": 16
        },
        {
          "time": "2026-10-09T10:00:00-04:00",
          "waitTime": 35,
          "percentage": 29
        },
        {
          "time": "2026-10-09T11:00:00-04:00",
          "waitTime": 50,
          "percentage": 41
        },
        {
          "time": "2026-10-09T12:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T13:00:00-04:00",
          "waitTime": 50,
          "percentage": 41
        },
        {
          "time": "2026-10-09T14:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T15:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T16:00:00-04:00",
          "waitTime": 30,
          "percentage": 25
        },
        {
          "time": "2026-10-09T17:00:00-04:00",
          "waitTime": 40,
          "percentage": 33
        },
        {
          "time": "2026-10-09T18:00:00-04:00",
          "waitTime": 45,
          "percentage": 37
        },
        {
          "time": "2026-10-09T19:00:00-04:00",
          "waitTime": 30,
          "percentage": 25
        },
        {
          "time": "2026-10-09T20:00:00-04:00",
          "waitTime": 30,
          "percentage": 25
        }
      ],
      "operatingHours": [
        {
          "type": "Early Entry",
          "endTime": "2026-10-09T08:30:00-04:00",
          "startTime": "2026-10-09T08:00:00-04:00"
        },
        {
          "type": "Operating",
          "endTime": "2026-10-09T21:00:00-04:00",
          "startTime": "2026-10-09T08:30:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T12:59:26.393Z"
    },
    {
      "id": "7357772c-6b11-4a8d-af97-05a1bb45f001",
      "name": "Indiana Jones™ Epic Stunt Spectacular!",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "136;entityType=Entertainment",
      "queue": {
        "RETURN_TIME": {
          "state": "FINISHED",
          "returnEnd": null,
          "returnStart": null
        }
      },
      "status": "OPERATING",
      "showtimes": [
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T10:45:00-04:00",
          "startTime": "2026-10-09T10:45:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T12:00:00-04:00",
          "startTime": "2026-10-09T12:00:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T13:15:00-04:00",
          "startTime": "2026-10-09T13:15:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T15:15:00-04:00",
          "startTime": "2026-10-09T15:15:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T16:30:00-04:00",
          "startTime": "2026-10-09T16:30:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T10:28:22.131Z"
    },
    {
      "id": "79860074-658f-49bc-8c1b-624af8b4718e",
      "name": "Meet Edna Mode at the Edna Mode Experience",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "19205017;entityType=Entertainment",
      "queue": {
        "STANDBY": {
          "waitTime": null
        }
      },
      "status": "CLOSED",
      "showtimes": [
        {
          "type": "Performance Time",
          "endTime": "2026-10-08T16:30:00-04:00",
          "startTime": "2026-10-08T09:00:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-08T20:31:03.106Z"
    },
    {
      "id": "7a73a6df-4d33-4648-b3e3-57985f84f0ae",
      "name": "Roundup Rodeo BBQ",
      "entityType": "RESTAURANT",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "19553134;entityType=restaurant",
      "status": "OPERATING",
      "lastUpdated": "2026-10-09T00:50:28.169Z"
    },
    {
      "id": "7bf05bdc-8279-427b-8a6d-50fc62ef31cb",
      "name": "Hollywood & Vine",
      "entityType": "RESTAURANT",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "90001744;entityType=restaurant",
      "status": "OPERATING",
      "lastUpdated": "2026-10-08T23:50:05.370Z"
    },
    {
      "id": "847ab726-3672-42fd-a232-df7a3fb2baf7",
      "name": "The Record Setters",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "412496812;entityType=Entertainment",
      "status": "CLOSED",
      "showtimes": [],
      "lastUpdated": "2026-09-09T04:02:10.570Z"
    },
    {
      "id": "90ab2c64-e05c-4783-bde5-fddf41f78402",
      "name": "Disney Movie Magic",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "18693119;entityType=Entertainment",
      "status": "OPERATING",
      "showtimes": [
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T20:40:00-04:00",
          "startTime": "2026-10-09T20:40:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T04:04:21.239Z"
    },
    {
      "id": "917783a5-da9c-4c55-ac51-0ac1f8253131",
      "name": "The Hollywood Brown Derby",
      "entityType": "RESTAURANT",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "90002245;entityType=restaurant",
      "status": "OPERATING",
      "lastUpdated": "2026-10-08T23:00:46.389Z"
    },
    {
      "id": "9211adc9-b296-4667-8e97-b40cf76108e4",
      "name": "Vacation Fun - An Original Animated Short with Mickey & Minnie",
      "entityType": "ATTRACTION",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "19497952;entityType=Attraction",
      "queue": {
        "STANDBY": {
          "waitTime": 10
        }
      },
      "status": "OPERATING",
      "forecast": [
        {
          "time": "2026-10-09T08:00:00-04:00",
          "waitTime": 15,
          "percentage": 12
        },
        {
          "time": "2026-10-09T09:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T10:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T11:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T12:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T13:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T14:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T15:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T16:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T17:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T18:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T19:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T20:00:00-04:00",
          "waitTime": 0,
          "percentage": 0
        }
      ],
      "operatingHours": [
        {
          "type": "Operating",
          "endTime": "2026-10-09T20:00:00-04:00",
          "startTime": "2026-10-09T08:30:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T12:38:08.336Z"
    },
    {
      "id": "a7763ca6-bca3-4e78-b75c-22886aa06bec",
      "name": "The Little Mermaid – A Musical Adventure",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "412328858;entityType=Entertainment",
      "queue": {
        "RETURN_TIME": {
          "state": "AVAILABLE",
          "returnEnd": "2026-10-09T13:00:00-04:00",
          "returnStart": "2026-10-09T12:00:00-04:00"
        }
      },
      "status": "OPERATING",
      "showtimes": [
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T10:00:00-04:00",
          "startTime": "2026-10-09T10:00:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T10:35:00-04:00",
          "startTime": "2026-10-09T10:35:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T11:10:00-04:00",
          "startTime": "2026-10-09T11:10:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T11:45:00-04:00",
          "startTime": "2026-10-09T11:45:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T12:20:00-04:00",
          "startTime": "2026-10-09T12:20:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T12:55:00-04:00",
          "startTime": "2026-10-09T12:55:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T13:30:00-04:00",
          "startTime": "2026-10-09T13:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T14:05:00-04:00",
          "startTime": "2026-10-09T14:05:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T14:40:00-04:00",
          "startTime": "2026-10-09T14:40:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T15:15:00-04:00",
          "startTime": "2026-10-09T15:15:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T15:50:00-04:00",
          "startTime": "2026-10-09T15:50:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T16:25:00-04:00",
          "startTime": "2026-10-09T16:25:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T17:00:00-04:00",
          "startTime": "2026-10-09T17:00:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T17:35:00-04:00",
          "startTime": "2026-10-09T17:35:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T18:10:00-04:00",
          "startTime": "2026-10-09T18:10:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T18:45:00-04:00",
          "startTime": "2026-10-09T18:45:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T19:20:00-04:00",
          "startTime": "2026-10-09T19:20:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T19:55:00-04:00",
          "startTime": "2026-10-09T19:55:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T12:34:08.939Z"
    },
    {
      "id": "b1ed574f-40f2-4132-a1ee-893a276633c8",
      "name": "Wonderful World of Animation",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "19260580;entityType=Entertainment",
      "status": "OPERATING",
      "showtimes": [
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T21:00:00-04:00",
          "startTime": "2026-10-09T21:00:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T04:04:21.264Z"
    },
    {
      "id": "bc2c2ffe-3cf0-4e75-a408-bf5e86515c4c",
      "name": "Green Army Drum Corps",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "19025720;entityType=Entertainment",
      "status": "OPERATING",
      "showtimes": [
        {
          "type": "Operating",
          "endTime": "2026-10-09T10:00:00-04:00",
          "startTime": "2026-10-09T10:00:00-04:00"
        },
        {
          "type": "Operating",
          "endTime": "2026-10-09T11:00:00-04:00",
          "startTime": "2026-10-09T11:00:00-04:00"
        },
        {
          "type": "Operating",
          "endTime": "2026-10-09T12:00:00-04:00",
          "startTime": "2026-10-09T12:00:00-04:00"
        },
        {
          "type": "Operating",
          "endTime": "2026-10-09T14:00:00-04:00",
          "startTime": "2026-10-09T14:00:00-04:00"
        },
        {
          "type": "Operating",
          "endTime": "2026-10-09T15:00:00-04:00",
          "startTime": "2026-10-09T15:00:00-04:00"
        },
        {
          "type": "Operating",
          "endTime": "2026-10-09T16:00:00-04:00",
          "startTime": "2026-10-09T16:00:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T04:04:21.245Z"
    },
    {
      "id": "c113b1cf-7b6d-416a-8e21-bf8f387ecd77",
      "name": "Meet Ariel at Walt Disney Presents",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "411926516;entityType=Entertainment",
      "queue": {
        "STANDBY": {
          "waitTime": null
        }
      },
      "status": "CLOSED",
      "showtimes": [
        {
          "type": "Performance Time",
          "endTime": "2026-10-08T15:45:00-04:00",
          "startTime": "2026-10-08T09:00:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-08T19:45:58.890Z"
    },
    {
      "id": "c600282c-227b-4ffc-b1ee-b5987609ee4f",
      "name": "50's Prime Time Café",
      "entityType": "RESTAURANT",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "90001216;entityType=restaurant",
      "status": "OPERATING",
      "lastUpdated": "2026-10-09T00:51:09.384Z"
    },
    {
      "id": "d07a17c2-7720-4db7-b12a-a68ecdb51108",
      "name": "Hollygroove Swingin’",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "412496861;entityType=Entertainment",
      "status": "CLOSED",
      "showtimes": [],
      "lastUpdated": "2026-09-07T04:02:26.984Z"
    },
    {
      "id": "d2af9650-9f91-45ef-98be-de44b4b44c32",
      "name": "The Hollywood Brown Derby Lounge",
      "entityType": "RESTAURANT",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "17571157;entityType=restaurant",
      "status": "OPERATING",
      "lastUpdated": "2026-10-08T23:50:40.099Z"
    },
    {
      "id": "d56506e2-6ad3-443a-8065-fea37987248d",
      "name": "Alien Swirling Saucers",
      "entityType": "ATTRACTION",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "18904172;entityType=Attraction",
      "queue": {
        "STANDBY": {
          "waitTime": 20
        },
        "RETURN_TIME": {
          "state": "AVAILABLE",
          "returnEnd": "2026-10-09T16:20:00-04:00",
          "returnStart": "2026-10-09T15:20:00-04:00"
        }
      },
      "status": "OPERATING",
      "forecast": [
        {
          "time": "2026-10-09T08:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T09:00:00-04:00",
          "waitTime": 15,
          "percentage": 12
        },
        {
          "time": "2026-10-09T10:00:00-04:00",
          "waitTime": 30,
          "percentage": 25
        },
        {
          "time": "2026-10-09T11:00:00-04:00",
          "waitTime": 40,
          "percentage": 33
        },
        {
          "time": "2026-10-09T12:00:00-04:00",
          "waitTime": 40,
          "percentage": 33
        },
        {
          "time": "2026-10-09T13:00:00-04:00",
          "waitTime": 40,
          "percentage": 33
        },
        {
          "time": "2026-10-09T14:00:00-04:00",
          "waitTime": 40,
          "percentage": 33
        },
        {
          "time": "2026-10-09T15:00:00-04:00",
          "waitTime": 25,
          "percentage": 20
        },
        {
          "time": "2026-10-09T16:00:00-04:00",
          "waitTime": 25,
          "percentage": 20
        },
        {
          "time": "2026-10-09T17:00:00-04:00",
          "waitTime": 25,
          "percentage": 20
        },
        {
          "time": "2026-10-09T18:00:00-04:00",
          "waitTime": 30,
          "percentage": 25
        },
        {
          "time": "2026-10-09T19:00:00-04:00",
          "waitTime": 30,
          "percentage": 25
        },
        {
          "time": "2026-10-09T20:00:00-04:00",
          "waitTime": 15,
          "percentage": 12
        }
      ],
      "operatingHours": [
        {
          "type": "Early Entry",
          "endTime": "2026-10-09T08:30:00-04:00",
          "startTime": "2026-10-09T08:00:00-04:00"
        },
        {
          "type": "Operating",
          "endTime": "2026-10-09T21:00:00-04:00",
          "startTime": "2026-10-09T08:30:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T12:59:26.238Z"
    },
    {
      "id": "d7669edc-eaa1-4af2-bbb5-6e98df564166",
      "name": "Walt Disney Presents",
      "entityType": "ATTRACTION",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "18770880;entityType=Attraction",
      "queue": {
        "STANDBY": {
          "waitTime": null
        }
      },
      "status": "OPERATING",
      "forecast": [
        {
          "time": "2026-10-09T08:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T09:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T10:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T11:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T12:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T13:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T14:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T15:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T16:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T17:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T18:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T19:00:00-04:00",
          "waitTime": 10,
          "percentage": 8
        },
        {
          "time": "2026-10-09T20:00:00-04:00",
          "waitTime": 0,
          "percentage": 0
        }
      ],
      "operatingHours": [
        {
          "type": "Operating",
          "endTime": "2026-10-09T20:00:00-04:00",
          "startTime": "2026-10-09T08:30:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T12:31:20.480Z"
    },
    {
      "id": "d91a0e9a-8652-4036-822f-e7b12b381273",
      "name": "For the First Time in Forever: A Frozen Sing-Along Celebration",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "17842841;entityType=Entertainment",
      "queue": {
        "RETURN_TIME": {
          "state": "AVAILABLE",
          "returnEnd": "2026-10-09T10:05:00-04:00",
          "returnStart": "2026-10-09T09:05:00-04:00"
        }
      },
      "status": "OPERATING",
      "showtimes": [
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T09:30:00-04:00",
          "startTime": "2026-10-09T09:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T10:30:00-04:00",
          "startTime": "2026-10-09T10:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T11:30:00-04:00",
          "startTime": "2026-10-09T11:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T12:30:00-04:00",
          "startTime": "2026-10-09T12:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T13:30:00-04:00",
          "startTime": "2026-10-09T13:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T14:30:00-04:00",
          "startTime": "2026-10-09T14:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T15:30:00-04:00",
          "startTime": "2026-10-09T15:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T16:30:00-04:00",
          "startTime": "2026-10-09T16:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T17:30:00-04:00",
          "startTime": "2026-10-09T17:30:00-04:00"
        },
        {
          "type": "Performance Time",
          "endTime": "2026-10-09T18:30:00-04:00",
          "startTime": "2026-10-09T18:30:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T12:59:26.402Z"
    },
    {
      "id": "d9dbd260-9e34-406d-abb7-19f9d733e577",
      "name": "Sci-Fi Dine-In Theater Restaurant",
      "entityType": "RESTAURANT",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "90002114;entityType=restaurant",
      "status": "OPERATING",
      "lastUpdated": "2026-07-08T16:24:05.788Z"
    },
    {
      "id": "e516f303-e82d-4fd3-8fbf-8e6ab624cf89",
      "name": "Rock ’n’ Roller Coaster Starring The Muppets",
      "entityType": "ATTRACTION",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "412573652;entityType=Attraction",
      "queue": {
        "STANDBY": {
          "waitTime": 35
        },
        "RETURN_TIME": {
          "state": "AVAILABLE",
          "returnEnd": "2026-10-09T15:25:00-04:00",
          "returnStart": "2026-10-09T14:25:00-04:00"
        },
        "SINGLE_RIDER": {
          "waitTime": null
        }
      },
      "status": "OPERATING",
      "operatingHours": [
        {
          "type": "Early Entry",
          "endTime": "2026-10-09T08:30:00-04:00",
          "startTime": "2026-10-09T08:00:00-04:00"
        },
        {
          "type": "Operating",
          "endTime": "2026-10-09T21:00:00-04:00",
          "startTime": "2026-10-09T08:30:00-04:00"
        }
      ],
      "lastUpdated": "2026-10-09T12:59:26.304Z"
    },
    {
      "id": "eb325677-d32a-41ec-b2c9-e1ab91bade02",
      "name": "Meet Pixar Pals at Pixar Plaza",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "411927635;entityType=Entertainment",
      "status": "OPERATING",
      "showtimes": [
        {
          "type": "Performance Time",
          "endTime": "2024-09-30T17:00:00-04:00",
          "startTime": "2024-09-30T09:00:00-04:00"
        }
      ],
      "lastUpdated": "2024-09-30T04:29:37.089Z"
    },
    {
      "id": "eea07a8d-30e0-42d8-9c47-58cc038801e8",
      "name": "Meet the Toys in Toy Story Land",
      "entityType": "SHOW",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "19205060;entityType=Entertainment",
      "status": "CLOSED",
      "lastUpdated": "2026-06-04T19:17:02.544Z"
    },
    {
      "id": "f020b5e3-d26d-4339-83f9-0f1f858a0e40",
      "name": "Oga's Cantina",
      "entityType": "RESTAURANT",
      "parkId": "288747d1-8b4f-4a64-867e-ea7c9b27bad8",
      "externalId": "19267226;entityType=restaurant",
      "status": "OPERATING",
      "lastUpdated": "2026-10-09T00:55:18.091Z"
    }
  ]
}